### PR TITLE
Move CollectionInterface beneath \Slim\Interfaces\Http namespace

### PR DESCRIPTION
**Pull request by zither**
see #1142 and #1146, my bad.

### CODE REVIEW

**Comment by lalop** [comment]
Why do you move CollectionInterace into Http ?

**Comment by JoeBengalen** [comment]
@lalop He did not, codeguy did. If I remember correctly he did it to prepare the separation of the Http classes into its own repo.

Edit:
Ohw nvm we are talking about the Interface ... But the answer is actualy the same. Codeguy moved the Collection class into Http, so it is consitent to put the Interface into Http as well.

**Comment by codeguy** [comment]
What @JoeBengalen said.

**Comment by lalop** [comment]
ok, I see

**Pull request merged**
