### PR TITLE
Lazy resolve Route middleware

### PR DESCRIPTION
**Pull request by mathmarques**
See https://github.com/slimphp/Slim/issues/1604

### CODE REVIEW

**Comment by akrabat** [comment]
This is the one that needs careful testing :)

**Comment by akrabat** [comment]
Ping @silentworks. Have you had a chance to look at this?

**Comment by jeremygiberson** [comment]
I sent a pull request for consideration as an alternative for this, please see #1716.

**Comment by akrabat** [comment]
Closed as #1716 is now merged.

**Pull request closed without merging**
