### PR TITLE
Path info is being calculated wrong when route and installation directory have the same name

### PR DESCRIPTION
**Pull request by falmp**
When Slim is installed on a subdirectory and a route with the same subdirectory name is called, PATH_INFO is calculated wrong. This bug seems to be introduced on 2.3.3 with commit a35767746009ff818e6375b72f23a2cf7de5f1a4 (Add HHVM compatibility)

These are the tests to trigger the bug.

```
There were 2 failures:

1) EnvironmentTest::testParsesPathsWithCommonPrefixForSubdirectoryAndRouteNameWithUrlRewriteInSubdirectory
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/foobar'
+'/bar'

2) EnvironmentTest::testParsesPathsWithCommonSubdirectoryAndRouteNameWithUrlRewriteInSubdirectory
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/foo'
+'/'
```

### CODE REVIEW

**Comment by codeguy** [comment]
Please test using the experimental Environment.php class shown here:

https://github.com/codeguy/Slim/issues/655#issuecomment-26771717

**Comment by falmp** [comment]
Yup, it works. :)

**Comment by codeguy** [comment]
Closing. This is fixed in the current release.

**Comment by falmp** [comment]
Ok, thank you Josh!

**Pull request closed without merging**
