### PR TITLE
make sure optional methods are callable

### PR DESCRIPTION
**Pull request by pine3ree**

### CODE REVIEW

**Comment by akrabat** [comment]
Was there a specific use-case you came across that prompted this change?

**Comment by silentworks** [comment]
I think this is to do with method visibility, I think `method_exists` will find private and protected methods even though they are unusable outside of their context.

**Comment by silentworks** [comment]
Yeah tested this and my thinking above is correct.

**Comment by lalop** [comment]
I think we should create a new interface that extends RouteInterface or some traits that define this methods but testing if the method exists doesn't seem to be a good partern since all is based on interface.

**Pull request merged**
