### PR TITLE
branch release-2.4.1 dropped without merging fixes?

### PR DESCRIPTION
**Pull request by qyanu**
Hi there,

you seem to have dropped the branch codeguy/Slim/release-2.4.1 without merging it into master.

Indeed by doing so a fix from me, accepted in a previous pull request, is not included in the tag 2.4.1.
Another commit by marcioAlmada (I don't know him, also have I only superficially inspected his commit) is also missing.

I have cherry-picked these commits onto qyanu/Slim/release-2.4.3.

Was the drop intentionally, a sort of post-accept rejection of the pull request?
Or just unintentionally (then I would be happy to help sorting out the git-tree).

Kind regards,

Max

### CODE REVIEW

**Comment by qyanu** [comment]
PS: the two pull requests where https://github.com/codeguy/Slim/pull/703 and https://github.com/codeguy/Slim/pull/715

**Comment by codeguy** [comment]
Ah that would have been unintentional. If you can help get those into the release-2.4.3 branch that would be great.

**Comment by qyanu** [comment]
@codeguy   Hi
- I have merged the lost release-2.4.1 branch (including all merge-commits) into release-2.4.3.
- I have closely inspected `git diff codeguy/release-2.4.3 codeguy/release-2.4.3 --` and everything allright.
- I have executed all phpunit tests and saw them all succeed
- in addition I feel bad for not adding a phpunit test on the occasion of the slim.after bug.

In conclusion: I recommend you just accept this pull request into codeguy/release-2.4.3  :-)

regards,
Max

PS:
- I transmitted the slim.after bugfix onto the develop branch, see https://github.com/codeguy/Slim/pull/787
- I'm not sure about your policy on how to transfer fixes from release-x.y.z to develop. is it "foreach($commits as $commit) { cherry_pick($commit); }"?

**Comment by marcioAlmada** [comment]
hey, @qyanu 

Thank you, I would never notice it.

**Comment by qyanu** [comment]
hey @marcioAlmada   :-)

maybe you can also ammend (if possible on github) https://github.com/codeguy/Slim/pull/787 in order to copy your fix onto the develop branch?

regards,
Max

**Comment by marcioAlmada** [comment]
Ok, I'll see if I can send you a pull request to your develop branch and then we merge both commits at once.

**Comment by marcioAlmada** [comment]
Well, it seems @codeguy already has commits from #715 on develop branch so your other pull request is all set :smile:

Anyway, thanks for pulling stuff to v2.4.3 again.

**Comment by qyanu** [comment]
ping?

**Pull request merged**
