### PR TITLE
Is this typos?

### PR DESCRIPTION
**Pull request by phpinfointh**
`isset($uploadedFile['tmp_name']) ? $uploadedFile['name'] : null`
should it be
`isset($uploadedFile['name']) ? $uploadedFile['name'] : null`

### CODE REVIEW

**Comment by mathmarques** [comment]
No, see: https://github.com/slimphp/Slim/issues/1673

**Comment by akrabat** [comment]
Looks like a bug to me. I don't understand from the manual page why it isn't. Input from @silentworks required!

**Comment by silentworks** [comment]
This is what the manual page states.
- $_FILES['userfile']['name']: The original name of the file on the client machine.
- $_FILES['userfile']['tmp_name']: The temporary filename of the file in which the uploaded file was stored on the server.

To me this says that the `tmp_name` is greater to check against as this is an actual place the files is store on the server and if it wasn't this would return none from what the docs says, while there is no mention on if `name` would even be a thing at this stage.

But saying that, after reading this comment http://php.net/manual/en/features.file-upload.post-method.php#104349 it might make more sense to check `name`.

**Comment by phpinfointh** [comment]
The reason I thought this was a typo is ...
If someone uses array data that `name` key is missing (maybe mocking data), this will result in PHP notice.

**Pull request merged**
