### PR TITLE
Add HEAD shortcut route

### LINKED ISSUE #2033: Why are we not supporting HEAD in routes?
Hello

I was implementing a route like this: 

```
$app->group('/pattern', function () {

    $this->get('', '\MyClass:getMethodOnController');
    $this->head('', '\MyClass:headMethodOnController');

});
```

And Slim just crashes because apparently it doesn't support HEAD for routing patterns. Why? Is this an oversight or is there a good reason for it? I find it odd because the `$request` object has the HEAD method available like `$request->isHead();`

I was encouraged to open an issue on Slack.

### PR DESCRIPTION
**Pull request by chadicus**
Fixes #2033

### CODE REVIEW

**Comment by codeguy** [comment]
Is there a reason you want to define routes that respond ONLY to head requests? You should already be able to issue HEAD requests  against any GET route, you just won't  get back the response body, just the header.

**Comment by codeguy** [comment]
See https://github.com/nikic/FastRoute#a-note-on-head-requests (which Slim uses under the hood)

**Comment by chadicus** [comment]
@codeguy I just saw the issue discussion and thought I'd lend a hand by adding the method. I have no use case for HEAD requests. Feel free to reject the PR.

**Comment by geggleto** [comment]
From FastRoute

> Finally, note that applications MAY always specify their own HEAD method route for a given resource to bypass this behavior entirely.

👍 for me.

**Comment by akrabat** [comment]
Not needed as no one has a use case for responding to HEAD differently to GET.

**Comment by garnold** [comment]
@akrabat https://github.com/slimphp/Slim/issues/2033#issuecomment-278341137

**Pull request closed without merging**
