### PR TITLE
Bumping version

### PR DESCRIPTION
**Pull request by danielgsims**
I opened this as a question really. Is the intention to bump the release with future versions? If so, it's grown stale. Thanks!

### CODE REVIEW

**Comment by geggleto** [comment]
we should probably drop this const :D /cc @akrabat

**Comment by danielgsims** [comment]
I did a quick search on github, and I found some folks using it :(

**Comment by geggleto** [comment]
Oh god no......

**Comment by akrabat** [comment]
I've updated `VERSION` for the 3.4.2 release and have set it on 3.x`to a`-dev`number. Don't trust the number on`3.x` though...

**Comment by codeguy** [comment]
This should be automated or removed imo.

**Comment by akrabat** [comment]
Yes - automation would be nice. We can't remove until 4.0…

**Comment by danielgsims** [comment]
Thanks @akrabat!

**Pull request closed without merging**
