### PR TITLE
Clarification for noobs

### PR DESCRIPTION
**Pull request by ghost**
I cloned the repo and started immediately on Hello World example, but hadn't yet read about .haccess (sorry, I'm a skimmer). 

So I added a mention to that setup step above the Hello World example.

(Is it incorrect that I'm doing a pull request to your `master` branch?)

### CODE REVIEW

**Comment by codeguy** [comment]
The examples at the top of the README are brief visual examples only to demonstrate how simple it is to write and run a Slim app. The Hello World tutorial and online documentation are available at http://www.slimframework.com/learn as is listed in the README and clearly linked to on the website. I encourage you to fully read the README and online documentation to learn how to use the framework as intended.

**Comment by ghost** [comment]
I agree I should have read the entire readme. But hello world is intended for complete newcomers to the framework, and it's given before the necessary setup details, which doesn't make sense.

**Comment by ghost** [comment]
Updated following your instruction, the new commit seems to be noted in this pull request above.

I hope there's not bad feelings :) Thanks for all the work.

**Comment by codeguy** [comment]
I've added these changes to the develop branch (and to the v1.6.0 release branch).

**Pull request closed without merging**
