### PR TITLE
Fix urlFor adding extra slashes on Windows OS #663

### PR DESCRIPTION
**Pull request by silentworks**

### CODE REVIEW

**Comment by codeguy** [comment]
Does this work when the physical directory path has more than one "\" in it?

**Comment by codeguy** [comment]
Picked into 2.3.5.

**Comment by tuupola** [comment]
Did you notice that some tests were failing?

**Comment by silentworks** [comment]
Re-testing now, I didn't realize that travisci is only running on develop branch.

**Comment by tuupola** [comment]
Actually the failed test is not caused by your commit. Instead it was some slow running test. Second changed before the test could finish.

```
1) SlimTest::testExpiresAsString
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Tue, 05 Nov 2013 00:37:01 GMT'
+'Tue, 05 Nov 2013 00:37:00 GMT'
```

**Comment by silentworks** [comment]
I seem to be getting the ViewTest failing and not the one you mentioned. Are you testing master branch?

**Comment by tuupola** [comment]
I am not testing myself. I saw it from the [details](https://travis-ci.org/codeguy/Slim/builds/13293406) link in the Travis CI build failed notification in this pull request.

**Comment by silentworks** [comment]
ah yes what you said would make sense.

**Comment by codeguy** [comment]
Yes, there's one test that will intermittently fail since it's coded poorly. It expects two time measurements to be the same, but they may differ by a second or so every once in a while. I need to fix that.

**Pull request closed without merging**
