### PR TITLE
URL encoding password

### PR DESCRIPTION
**Pull request by Sam-Burns**
Fix https://github.com/slimphp/Slim/issues/2201

### CODE REVIEW

**Comment by geggleto** [comment]
Can you URL Encode the user too... for obvious reasons X_X

**Review by Rudloff — APPROVED** [review]
I confirm this fixes my usecase.

**Comment by ghost** [comment]
First: You should use `rawurlencode` not `urlencode`.
Second: Take a look at [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.2) you will get that your encoding is wrong.

**Review by akrabat — APPROVED** [review]

**Comment by akrabat** [comment]
Should this be against `3.x` ?

**Comment by akrabat** [comment]
@sharifzadesina  if it's changed to rawurlencode, what is then wrong?

**Comment by akrabat** [comment]
@Sam-Burns rebase required.

**Comment by ghost** [comment]
@akrabat 
You must use a function like below one for encoding:
```php
[...]
    /**
     * Sets the URI user information.
     *
     * @param string      $user
     * @param string|null $password
     */
    private function setUserInfo($user, $password = null)
    {
        $this->userInfo = '';

        if ('' !== $user) {
            $this->userInfo = self::encodeUserInfo($user);
            if ('' != $password) {
                $this->userInfo .= ':' . self::encodeUserInfo($password);
            }
        }
    }

    /**
     * Encodes URI user information.
     *
     * @see https://tools.ietf.org/html/rfc3986#section-3.2.1
     *
     * @param string $string User information
     *
     * @return string Encoded user information
     */
    private static function encodeUserInfo($string)
    {
        return preg_replace_callback(
            '#(?:[^' . self::CHAR_UNRESERVED . self::CHAR_SUB_DELIMS . ':%]+|%(?![A-Fa-f0-9]{2}))#',
            function ($matches) {
                return rawurlencode($matches[0]);
            },
            $string
        );
    }
[...]
```

**Comment by akrabat** [comment]
Needs to be against Slim-Http now. Also, should we be encoding only on output?

**Pull request closed without merging**
