### PR TITLE
Fix output buffering issue that was creating a risky test in PHPUnit.

### PR DESCRIPTION
**Pull request by Rezouce**
Same problem as here but at the Route level:
https://github.com/slimphp/Slim/pull/2333

It fixes the risky test for `RouteTest::testInvokeWithException`.

### CODE REVIEW

**Comment by moritz-h** [comment]
@Rezouce Would it make sense to also use `ob_get_contents()` instead of `ob_get_clean()` here: https://github.com/slimphp/Slim/blob/3.9.0/Slim/Handlers/Error.php#L61-L64
and remove it here: https://github.com/slimphp/Slim/blob/3.9.0/Slim/Handlers/Error.php#L68
Otherwise I think in the finally block the buffer would be destroyed a second time in exception case.

**Comment by akrabat** [comment]
Travis test fails.

**Comment by Rezouce** [comment]
@moritz-h you are right, I didn't see that the output buffering management was duplicated in the error handler.
Instead of duplicating the logic in both the route and the error handler, I chose to move the output buffering management at the app level instead.

**Comment by akrabat** [comment]
I'm wondering if anyone depends on output buffering being at route level.

**Review by silentworks — APPROVED** [review]

**Review by RyanNerd — CHANGES_REQUESTED** [review]
In `Slim/Slim/Handlers/AbstractError.php` in the constructor the second argument is [`$outputBuffering`](https://github.com/slimphp/Slim/blob/c9a768c5a062c5f1aaa0a588d7bb90e8ce18bfd6/Slim/Handlers/AbstractError.php#L31) since this is being moved to the App level this class should no longer need this argument.
Also`PhpError.php` which extends `AbstractError` should be looked at to see if it is using the `$outputBuffering` setting.

**Comment by akrabat** [comment]
Do we break anything if we remove a parameter to a constructor?

**Comment by moritz-h** [comment]
The `$outputBuffering` constructor parameter was just recently added with Slim 3.9.0. All usages within the handler are also removed with this PR.
But on calling the constructor the parameter should then also be removed:
https://github.com/slimphp/Slim/blob/3.9.0/Slim/DefaultServicesProvider.php#L157

**Comment by Rezouce** [comment]
I removed the unnecessary output buffering from the AbstractError, thank you @RyanNerd and @moritz-h for your inputs.
@akrabat I don't think removing this extra parameter will provoke any breaking change. Some people may continue to provide it but that shouldn't be a problem.

**Pull request merged**
