### PR TITLE
Dont need to check if some variable or functions are true

### PR DESCRIPTION
**Pull request by prisis**
We dont need to check if is_null === true or function_exists or $this->env->has($key)

or?

### CODE REVIEW

**Comment by strngr** [comment]
php.net docs:
`is_null`

> Returns TRUE if var is null, FALSE otherwise.

`function_exists`

> Returns TRUE if function_name exists and is a function, FALSE otherwise.

So what's the point to compare strictly results of `is_null` and `function_exists`?

**Comment by prisis** [comment]
i don't see any point to do it, because we can only get true or false.

**Comment by strngr** [comment]
I agree

**Comment by prisis** [comment]
I did use slim for my framework, ok is not more really slim and i did remove all strict results, and it works fine :)

**Comment by codeguy** [comment]
Agreed. Can you rebase against the latest code?

**Pull request closed without merging**
