### PR TITLE
Feature interfaces

### PR DESCRIPTION
**Pull request by designermonkey**
This is incomplete as I add the PR, but I'm losing track of where I am with it.

@csdco has expressed an interest in this, and a fresh pair of eyes would help.

Currently, there are interfaces for _most_ of the framework. While doing this (twice), I've started to question the need for some interfaces, the Collection class doesn't really need one, as it's a core component IMO. Many classes using it have interfaces, and if these were replaced, technically the developer could just use their own collection class.

You may also notice that I have blank interfaces for Cookies and Headers. I want to have a play with how this is currently implemented, and when done, there will need to be interfaces.

I think I have missed some parts, more than likely around the Request and Response area, but I can't tell now.

I need some others to look over this and let me know thoughts and changes, and I can then get them done.

cc @codeguy

### CODE REVIEW

**Comment by designermonkey** [comment]
I will rebase this again before a pull, as there are too many commits here.

**Comment by charlie-s** [comment]
I'm digging into the code and commits now to get the hang of things. Looking forward to it.

**Comment by designermonkey** [comment]
I knew I'd missed things ;) Thanks, I'll add that now.

**Comment by designermonkey** [comment]
It makes sense that as Slim still fully supports 5.3.x, the interface should be fully part of Slim. I'll do that.

**Comment by charlie-s** [comment]
Nice :) I'm looking at Request and Response next. Anywhere else you'd recommend I start? You can also email me, it's listed on my profile page.

Last question for the moment – all of this is being done against Slim 3.5. Should we port this stuff to the 4.0 codebase?

**Comment by charlie-s** [comment]
My thoughts on the `Collection` class – even though it's a core component and an interface for it might seem like unnecessary cruft, I always like that interfaces provide a summary of the contract between one class and other classes that extend or use it.

**Comment by designermonkey** [comment]
> Last question for the moment – all of this is being done against Slim 3.5. Should we port this stuff to the 4.0 codebase?

Did you mean `2.5` and `3.0`? We are doing this work for a breaking release of `3.0`, which is shaping up to be mega awesome.

The Request and Response classes are where I lost my way a bit. Last I looked was a very tired me at 1am, so I closed the laptop and slept. There may be bits missing, so looking here and checking if all methods required by the App class are present makes sense.

> My thoughts on the Collection class...

These are actually my thoughts too, but I didn't want to just overload Slim with interfaces. I am happy to make more, as there are many classes in the setup that extend the Collection.

I will also stick an Environment interface in there as well, even though it will be empty for now. A question has arisen about CLI use of Slim, and yes, making interfaces for every class would help if we start making changes along those lines too.

@csdco thanks for your time so far looking through this, all help is appreciated.

**Comment by designermonkey** [comment]
Plans have suddenly changed this evening as I opened up Sublime to work on this. I will crack on tomorrow now.

**Comment by charlie-s** [comment]
Sorry, I meant 2.3.5 and 2.4.0. Not enough coffee apparently. 

I was just comparing a local pull of 2.4.0 where I have class `Slim` (Slim/Slim.php) instead of `App` (Slim/App.php), it no longer extends `\Pimple`, etc. But after browsing through the commit history on the master branch, I'm a bit confused because your branch shows 2.3.5 but has App.php, my pull of 2.4.0 has Slim.php, but browsing the repo's latest commits shows it's currently App.php.

I'm thinking this is all because the latest work is being done on the `develop` branch which hasn't changed any version tags since 2.3.5 – is that correct or am I missing something else? 

Enjoy your evening :)

**Comment by designermonkey** [comment]
That's correct, yep. All intermediary work, @codeguy is doing in release branches.

John Porter.

**Comment by charlie-s** [comment]
Regarding `\Slim\Http\Request` – it looks to me like the interface you defined works with all interactions within Slim.

**Comment by charlie-s** [comment]
`\Slim\App.php` uses `\Slim\Http\Response::getMessageForCode($status)`. Should this then be accounted for in `\Slim\Interfaces\Http\ResponseInterface`? I realize that historically putting a static method in an interface doesn't make a lot of sense, but as of PHP 5.3 with late static bindings you can do:

```
$foo = new Foo();
$foo::someStaticMethod();
```

so this is potentially helpful to have in the interface.

Otherwise I also saw this interface matching up with `\Slim\Http\Response`'s usage.

**Comment by designermonkey** [comment]
Noted, I can add that too.

**Comment by charlie-s** [comment]
Can I commit to this branch or would I have to fork and send PRs to you? I'm happy to pass commits along for your review. Also started on the Container interface and could share that.

**Comment by designermonkey** [comment]
I've given you collaborator access so you can push to my repository. Feel free to make any additions and changes, I can always alter anything if need be.

**Comment by charlie-s** [comment]
Thanks! Just pushed initial work on the `CollectionInterface`. 

The `encrypt()` / `decrypt()` methods are used in App, and both require that the class implements `\IteratorAggregate`. Is there a way to define an interface that must also implement other interfaces, or do we need to consider an abstract class for `Collection`?

Something like:

```
interface CollectionInterface
{
    // ...
}

abstract class AbstractCollection implements \Countable, \IteratorAggregate
{
    public function count()
    {
        return count($this->data);
    }

    public function getIterator()
    {
        return new \ArrayIterator($this->data);
    }
}

class Collection extends AbstractCollection implements \Slim\Interfaces\CollectionInterface {
    // ...
}
```

I could be way off, just thinking.

**Comment by designermonkey** [comment]
I don't know about the Abstract idea, what does @codeguy think?

**Comment by charlie-s** [comment]
Just fixed the issue that I introduced between `Slim\Interfaces\CollectionInterface` and `Slim\Collection`'s `replace()` method. I should have ran phpunit before I pushed but I wanted to get the code up for you to see. 

The abstract thing could well be overkill, but after looking at how the Collection class is iterated over in the `encrypt()` / `decrypt()` and such, it seems like you may have to add an abstract class that implements `IteratorAggregate`, `Countable`, and potentially handles `encrypt()` and `decrypt()`, or just ignore them all from an interface perspective. That maybe defeats the purpose since they are called from App and elsewhere... which all goes back to your first point about Collection not really requiring an interface.

**Comment by designermonkey** [comment]
I wanted to refactor the Collection to extend Pimple itself and adjust the behaviour slightly. I had a chat with @codeguy about it. I'm too tired right now to figure if that would have an impact on what we're doing here or not.

**Comment by designermonkey** [comment]
I've had a good old think about this one, and I think I've come up with a clean solution (I think being the operative statement there).

For class interfaces where the class extends another, the interface should extend the the inherited one

```
class Headers extends Collection
{

}

interface HeadersInterface extends CollectionInterface
{

}
```

For classes implementing multiple interfaces, like Collection, then we should do something like the following

```
interface CollectionInterface extends IteratorAggregate
{
    // Include defined methods from the Countable interface
}
```

What do you think?

I want to have `Collection` extend `Pimple` as well, and in doing so, I will make a `PimpleInterface` doing similar.

**Comment by codeguy** [comment]
Sorry, just catching up on this thread. I'd like to avoid using abstract classes and stick with interfaces only. If that means we have to adjust some of Slim's implementation to make interfaces easier, that's fine.

**Comment by charlie-s** [comment]
+1 to avoiding abstracts; keep it slimmer :)

@designermonkey that sounds great. I can play with the `CollectionInterface` and push some code for you to review.

**Comment by designermonkey** [comment]
Again, I very much doubt this is going to merge cleanly. I've rebased the develop branch into this one today, and it caused a real mess. I'm in progress cleaning it up, and also re-thinking some of the interfaces...

An example is the Request interface. We have only listed public methods that are required by the App class, but I think it should have public methods that we would expect the implementing class to be able to handle. IMO, it's better to say "Slim expects a class to be able to do the following.", rather than "This is the bare minimum that Slim requires to function.".

**Comment by charlie-s** [comment]
Regarding `Request`, do you think the interface should require the `->is{Method}()` methods? (e.g. `isPost()`)? Also stuff like `getQueryString()`, `getProtocol()`?

**Comment by designermonkey** [comment]
I've gone through and made my personal judgement on that.

> do you think the interface should require the ->is{Method}() methods?

Yes, and I've also added the `->{Method}` functions as well, like `post` and `get`.

When it comes to the others, I've only added a few that, personally, I would deem required for an HTTP framework. Some of them are just accessors for the headers object, and so aren't so needed, but others are IMO.

I'm nearly ready to push again, so take a look later on.

**Comment by designermonkey** [comment]
Ok. All done as far as I can see.

@codeguy I've just test merged this using squash-commits also (as there are way too many for a normal history), and everything was ok with the world.

@csdco, if you want to add anything, please take a look through and let me know.

Also, I've gone with the idea of extending interfaces, but we still need to have a think about the multiple implementing classes, as just adding the interface methods is not quite right. It will ensure the methods are present, but I don't know if there's some PHP magic to how interfaces like `ArrayAccess`, `IteratorAggregate` and `Countable` work, as these are the only three we may see issues with.

If anyone else reading this thread has ideas, please feel free to let us know.

**Comment by charlie-s** [comment]
Can't we extend multiple interfaces in an interface? e.g.

```
interface CollectionInterface extends \ArrayAccess, \Countable, \IteratorAggregate
```

I honestly haven't used Countable and IteratorAggregate before, and have only touched ArrayAccess on occasion, but the methods they call don't seem to be very complicated:

```
public function count()
{
    return count($this->values);
}
...
public function getIterator()
{
    return new \ArrayIterator($this->values);
}
```

etc. The only way to tackle this that I'm aware of would be an abstract class.

Also, is it odd that `protected $values = array();` is declared in `Pimple`, but `CollectionInterface` doesn't extend Pimple and `$this->values` is always assumed to at least be an empty array?

**Comment by designermonkey** [comment]
I haven't read anywhere that interfaces can extend multiple others. Classes certainly can't do that.

Also, interfaces can't extend classes, so `Collection` could never extend `Pimple`. I will ask @fabpot whether he would provide a `PimpleInterface` and see what the answer is.

We could certainly add the protected property to `Collection` to ensure it is set, but `Collection` does extend `Pimple`, so I saw this as pointless.

**Comment by charlie-s** [comment]
Apparently interfaces can extend multiple interfaces, but classes certainly cannot. Check out example 3 @ php.net: http://php.net/language.oop5.interfaces#language.oop5.interfaces.examples.ex3

You're absolutely correct, it can't extend Pimple. I think I was just trying to illustrate that the interface doesn't require that property, so in the event that someone uses the `CollectionInterface` without `Pimple` they've got an object that begins throwing lots of errors because `$this->values` isn't set.

**Comment by designermonkey** [comment]
> Apparently interfaces can extend multiple interfaces

Well, I never spotted that! Damn! (goes to do some more work).

> so in the event that someone uses the CollectionInterface without Pimple they've got an object that begins throwing lots of errors because $this->values isn't set.

How so? the interface doesn't reference `$this->values` anywhere, it's the class that does, and the class would be replaced when someone uses the interface.

**Comment by charlie-s** [comment]
Fair point! I guess I'm looking at `count()`, `getIterator()`, etc., and was stuck in the mindset that those would be defined elsewhere and therefore the class would depend on the `values` property. I think you're spot on and it's a moot point.

**Comment by designermonkey** [comment]
@codeguy, I think this is ready to pull :D

**Comment by designermonkey** [comment]
This gives me a nice warm feeling inside :)

**Comment by codeguy** [comment]
:+1:

**Pull request merged**
