### PR TITLE
Fix getPort() following psr-7 spec

### PR DESCRIPTION
**Pull request by JoeBengalen**
Following the discussion in #1110 

``` php
// If a port is present, and it is non-standard for the current scheme, this method MUST return it as an integer.
$uri = new Slim\Http\Uri('https', 'www.example.com', 80);
var_dump($uri->getPort());
// result -> 80

// If the port is the standard port used with the current scheme, this method SHOULD return null.
$uri = new Slim\Http\Uri('http', 'www.example.com', 80);
var_dump($uri->getPort());
// result -> null

// If no port is present, and no scheme is present, this method MUST return a null value.
$uri = new Slim\Http\Uri('', 'www.example.com');
var_dump($uri->getPort());
// result -> null

// If no port is present, but a scheme is present, this method MAY return the standard port for that scheme, but SHOULD return null.
$uri = new Slim\Http\Uri('http', 'www.example.com');
var_dump($uri->getPort());
// result -> null
```

Let me know what you think!

### CODE REVIEW

**Comment by codeguy** [comment]
Are these backed up with tests?

**Comment by JoeBengalen** [comment]
If this is OK I will add tests for the cases shown above.

**Comment by codeguy** [comment]
:+1: Go for it

**Comment by JoeBengalen** [comment]
@codeguy Tests updated!

**Pull request merged**
