### PR TITLE
Convenient helper method

### PR DESCRIPTION
**Pull request by kminek**
express js-alike method :)

### CODE REVIEW

**Comment by nunocodex** [comment]
I like it +1

**Comment by mnapoli** [comment]
:+1:

**Comment by JoeBengalen** [comment]
Should `OPTIONS` be included?

**Comment by mnapoli** [comment]
It is.

**Comment by JoeBengalen** [comment]
It is indeed, but should it be? Has a whole different meaning compared to the other http methods.

**Comment by mnapoli** [comment]
Ah sorry I thought you were asking to include it.

All means all to me ;) (i.e. I want to catch all methods) I don't see why it should be "all but options".

**Comment by JoeBengalen** [comment]
True, just not too sure about what would be more useful. 

Also in Slim v2 there is a method called `any`. Isn't this the same functionality?
https://github.com/slimphp/Slim/blob/master/Slim/Slim.php#L563

**Comment by silentworks** [comment]
Can you rename the method to `any` please? that way it will keep the same naming as it did in Slim 2.

**Comment by kminek** [comment]
@silentworks done

**Comment by silentworks** [comment]
@kminek sorry for the delay in getting back to you, but can we have a unit test for this method please?

**Comment by silentworks** [comment]
Thank you very much for your contribution.

**Pull request merged**
