### PR TITLE
Fix route middleware stacks

### PR DESCRIPTION
**Pull request by mathmarques**
See https://github.com/slimphp/Slim/issues/1622

Removed the array_unshift from RouteGroup->add(), since Route->add() don't use it. Consistency on middleware arrays.

### CODE REVIEW

**Comment by codeguy** [comment]
Does this work for you? Can you add a unit test for this change?

**Comment by mathmarques** [comment]
Yes, works fine. I'll try to add some tests 'cause I'm not that good on phpunit stuffs...

**Comment by mathmarques** [comment]
Added tests

**Comment by codeguy** [comment]
Thanks!

**Pull request merged**
