### PR TITLE
Add Composer Compatibility

### PR DESCRIPTION
**Pull request by silentworks**
added in composer compatibility

### CODE REVIEW

**Comment by codeguy** [comment]
This is done. Pulled into both the develop and release-1.6.0 branches. Can you confirm it works correctly?

**Comment by silentworks** [comment]
This works correctly Josh. I tested from develop branch and it works without any issues.

**Comment by codeguy** [comment]
Great! Thanks for checking.

**Comment by bencevans** [comment]
@codeguy Are you adding it to http://packagist.com ?

**Comment by silentworks** [comment]
Yes this will be added to Packagist soon.
On Apr 14, 2012 9:58 PM, "Ben Evans" <
reply@reply.github.com>
wrote:

**Comment by bencevans** [comment]
Cheers :)

**Comment by silentworks** [comment]
This is now available on Packagist.

**Pull request closed without merging**
