### PR TITLE
Blade like templates

### PR DESCRIPTION
**Pull request by Gufran**
Blade like templating. Now developers can format the template using blade syntax like 
{{ $variable }}
@if...@elseif...@else, 
@foreach etc.

Templating is not full blown Blade but just a little part of it. only a limited set of methods is available.

Echoing variables in curly braces e.g. {{ $some_variable }} and {{{ $escaped_string }}}
blade like comments e.g. {{-- this is a comment --}}
including other view file using @include('some_other_view'), 
and these control structures:
@if .. @endif
@if .. @elseif .. @endif
@while .. @endwhile
@for .. @endfor
@foreach .. @endforeach
are implemented

### CODE REVIEW

**Comment by StJudeWasHere** [comment]
It would be great to have Blade templating support in Slim but in my opinion this should go in Slim-Extras, just like we do with Twig, Smarty and all the others.

**Comment by miraage** [comment]
You are welcome to create new extra view.
https://github.com/codeguy/Slim-Extras/tree/master/Views

**Comment by Gufran** [comment]
I completely understand the point here. If you can just spare some time to have a look into diff you'll find just a bunch of functions to perform some basic parsing to make template look cleaner and feature rich as well. I dont think we need to roll out a separate library for those tiny functions.
Anyway, I implemented this for my personal use because I was missing my Laravel way of managing html. Thought of sharing with everyone so here it is.

**Comment by codeguy** [comment]
This is not something that will be added to the core repo. You are welcome to create a custom view and submit a PR to the Slim-Extras repo.

**Pull request closed without merging**
