### PR TITLE
Optimize performance for Helper\Set\get()

### PR DESCRIPTION
**Pull request by wudi**
Not necessary repetitious  call normalizeKey method.

### CODE REVIEW

**Comment by lalop** [comment]
Hello,
the master branch only merge security pull request.

**Comment by wudi** [comment]
OK Thanks.
Now can i push to develop branch?

**Comment by lalop** [comment]
This class doesn't exist anymore on develop branch but any pr is welcome :)

**Comment by wudi** [comment]
@lalop  Where's the push requests for Slim like improving, optimize performance?
:)

**Comment by lalop** [comment]
https://github.com/slimphp/Slim/pulls
They seems to be closed and/or merged

**Comment by akrabat** [comment]
Set has been replaced by Pimple for the next version of Slim.

**Pull request closed without merging**
