### PR TITLE
Namespaced SLIM

### PR DESCRIPTION
**Pull request by kinncj**

### CODE REVIEW

**Comment by codeguy** [comment]
Slim still supports PHP 5.2 so I have chosen not to implement namespaces at this point in time. It also appears that your changes break many of Slim's unit tests, and you've made a change to the README that indicates you are maintaining a separate official namespaced branch of Slim which is not the case. I appreciate your suggested changes, but I'm not ready to pull these changes at this time.

**Comment by kinncj** [comment]
Not a problem to me begin with just like a fork of Slim, supporting namespaces...
I see that you read the "readme", so, you saw that the tests was broken and that the community will contribute with this...

Thanks for your appreciationm not a problem with the negative pull request...
Maybe when 5.4 comes and 5.2 down, we can maintain a version with namespaces and a 5.4 with some traits architecture...

Thanks yet.

**Comment by kinncj** [comment]
Like we talk over mail, the README was updated with the MIT instead of LGPL license.
The links to slim repository was updated too, but i remove the links to installation, support and others... i don't have any kind of wiki to namespaced version...

Can we do the same with the extensions?

**Comment by codeguy** [comment]
@kinncj As we discussed privately via email, I appreciate you making changes to the README to make it clear that your fork is based on my code rather than claiming it as your own. Can you make sure the README contains these changes?
1. Include a link to the authoritative Slim repository at https://github.com/codeguy/Slim
2. Retain a link to the @slimphp Twitter account
3. Retain all original copyright statements at the top of each framework file

I encourage everyone to fork my repository and submit pull requests so long as you respect the MIT license and provide credit to me, the original author.

**Comment by kinncj** [comment]
I don't know where do you whant the link to the Repository, it's in all the readme... i create a new section for this, so, another link to this.

The copyright statements still the same, just added the @author property to files with namespaced to my progile.

the link to twitter was added ;)

something more?

**Comment by codeguy** [comment]
The README is fine. I'm considering this resolved.

**Pull request closed without merging**
