### PR TITLE
Use the same middleware mecanism for App and Route

### PR DESCRIPTION
**Pull request by lalop**
This is a work in progress.
The target is to build a common entity that can manage app middleware's stack as well as the route middleware's stack

### CODE REVIEW

**Comment by lalop** [comment]
That 's is ready for review

**Comment by lalop** [comment]
@codeguy since the Middleware class is exists only for internal business I think we can transform it into a more abstract class to wrap the app to, to do it we just have to make the next param optinal.
Since it shouldn't be used outside of the library that seems ok for me. Maybe we should change its name.

**Comment by codeguy** [comment]
Ok, this is next on my todo list. Will be posting feedback soon.

**Comment by codeguy** [comment]
Here's some basic code I put together really quick based on what you've done so far. Let me know what you think. Basically, all we'd need to do is change the `Middleware` class in this code to a trait, and drop that into the `Slim` and `Route` classes.

``` php
<?php
class Middleware
{
    protected $stack = [];

    public function initializeStack()
    {
        $this->stack[] = $this;
    }

    public function add(callable $callable)
    {
        $next = $this->stack[0];

        array_unshift($this->stack, function ($req, $res) use ($callable, $next) {
            return $callable($req, $res, $next);
        });
    }

    public function call($req, $res)
    {
        return $this->stack[0]($req, $res);
    }

    public function __invoke($req, $res)
    {
        $res .= '-CENTER-';
        return $res;
    }
}

$mw = new Middleware();
$mw->initializeStack();
$mw->add(function ($req, $res, $next) {
    $res .= 'Foo';
    $res = $next($req, $res);
    $res .= 'Bar';

    return $res;
});
$mw->add(function ($req, $res, $next) {
    $res .= 'Xyz';
    $res = $next($req, $res);
    $res .= '123';

    return $res;
});
$out = $mw->call('', '');

echo $out;
```

**Comment by codeguy** [comment]
So much has changed I went ahead and implemented a rudimentary version in https://github.com/slimphp/Slim/commit/f45fe83c6f976210b5b334229bd406cc932db00e. Can you look over and make sure it's ok? Also, can you integrate into the Route class and make sure Route middleware is working correctly?

**Comment by lalop** [comment]
Hello.
Afk for the all week.
I will take a look next week.
Just to be sure you want me to add your implementation in the route class ?
Do we leave my pr ?

**Comment by codeguy** [comment]
I think your existing PR can be closed, but open a new PR for new changes and we can move discussions there.

**Pull request closed without merging**
