### PR TITLE
Send Exception also into NotFoundHandler

### PR DESCRIPTION
**Pull request by ghost**
**Motivation:** To be able to pass some aditional information into ErrorHandler.

### CODE REVIEW

**Comment by akrabat** [comment]
Can you explain the use-case a little more please as you didn't update the `NotFound` handler.

**Comment by ghost** [comment]
When I raise some exception (for example: `PostNotFoundException`, `UserDoesNotExistsException`), it's handy (especially for inner APIs) to provide aditional info about error into response body.

With this you can inhert your own NotFoundException (with meta info - message text for example) and in your presenters repack your domain exceptions into this one.

Api 404 responses now can be richer with some body info.

**Comment by ghost** [comment]
Also - it's expects you to have your own NotFoundHandler.

**Comment by ghost** [comment]
A can update default one to take this exception in declaration but as it wont be used - im not sure its the right thing to do.

**Pull request merged**
