### PR TITLE
App tests

### PR DESCRIPTION
**Pull request by dopesong**
Got commit from #2079 because accidently made changes in 3.x and rebased from it.

### CODE REVIEW

**Comment by akrabat** [comment]
I get this:

```
$ phpunit
PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

...............................................................  63 / 566 ( 11%)
.......................................WS...................... 126 / 566 ( 22%)
............................................................... 189 / 566 ( 33%)
..SSSSSSSSSSSSS................................................ 252 / 566 ( 44%)
............................................................... 315 / 566 ( 55%)
............................................................... 378 / 566 ( 66%)
............................................................... 441 / 566 ( 77%)
.........R..................................................... 504 / 566 ( 89%)
..............................................................  566 / 566 (100%)

Time: 615 ms, Memory: 18.00MB

There was 1 warning:

1) Slim\Tests\AppTest::testIsEmptyResponseWithoutEmptyMethod
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead

/Users/rob/Dropbox/bin/phpunit:572

WARNINGS!
Tests: 566, Assertions: 908, Warnings: 1, Skipped: 14, Risky: 1.
```

**Comment by dopesong** [comment]
Strange. Which php + phpunit version? Because travis passed.

**Comment by dopesong** [comment]
@akrabat should be ok now.

**Comment by geekish** [comment]
Just chiming in with a suggestion... it might help to suggest that devs use `vendor/bin/phpunit` instead of a global install so everyone is writing and running tests on the same(-ish) version. Definitely run into this before...

**Pull request merged**
