### PR TITLE
Related to #1962. Implementation with UnitTest

### PR DESCRIPTION
**Pull request by geggleto**
https://github.com/slimphp/Slim/pull/1962

### CODE REVIEW

**Comment by akrabat** [comment]
Please put `setCallable()` immediately after `getCallable()`.

Also, while we're here, can we add a protected property for $this->callable?

**Comment by mathmarques** [comment]
@akrabat $callable is already protected, [see here](https://github.com/slimphp/Slim/blob/3.x/Slim/Routable.php#L28).

**Comment by geggleto** [comment]
@mathmarques makes more sense to surface it for readability... I thought it was super weird that it was buried.

**Comment by akrabat** [comment]
ah! - it's in the parent…

**Comment by geggleto** [comment]
@akrabat I moved the method as well ;)

**Pull request merged**
