### PR TITLE
Try running unit tests on HHVM

### PR DESCRIPTION
**Pull request by ptarjan**

### CODE REVIEW

**Comment by cbschuld** [comment]
@ptarjan what has your experience been running Slim apps via HHVM - any experience to share?  I am clearly asking in the wrong medium but more curious on your experience!  Thx//cbs

**Comment by ptarjan** [comment]
@cbschuld I've just been running small sample apps to make sure your framework works on HHVM (they've all worked). I'm not using it for any actual deployments, I work on HHVM and just wanted to make sure other users can use HHVM with slim.

**Comment by cbschuld** [comment]
@ptarjan thx for the reply; I am going to put our app up on it in the next week & see how it goes... the performance increase sounds amazing - thx for your work on it

**Comment by codeguy** [comment]
Thanks. I need to create a new VM locally with the latest hhvm build for testing. Will get this merged into the 2.4.1 release this weekend.

**Comment by codeguy** [comment]
Merged into release-2.4.1 branch.

**Comment by codeguy** [comment]
@ptarjan Still getting some PHPUnit phar issues that cause unit tests to fail. See:

https://travis-ci.org/codeguy/Slim/jobs/15450484

Did a quick Google search and found this:

https://github.com/facebook/hhvm/issues/1334

**Pull request closed without merging**
