### PR TITLE
Able to pass arg to group route callback

### PR DESCRIPTION
**Pull request by garyyeap**
will let us have ability to pass args to callback of group route : 

```
$app->group('/:foo/bar', function($foo) use($app)
{
    echo $foo;
    $app->get('/whatever', ....
});
```

### CODE REVIEW

**Comment by endel** [comment]
Hey, the feature wasn't released yet? I'm running version 2.3.5 but this isn't working. Thanks!

**Comment by melbichon** [comment]
Please, can you add this feature in next release ?
Seems branch merging did not include commits.

**Comment by piotr-cz** [comment]
I'd really appreciate this feature.
It's a must when using language prefix as a segment in routes.

**Comment by codeguy** [comment]
Assigned this to @gmanricks. He'll review and pull in when appropriate.

**Comment by garyyeap** [comment]
Hi @piotr-cz , if you want to use with language prefix, here is an idea of middleware implementation that  no longer need to include language prefix param in any routes.

```
class I18N extends \Slim\Middleware
{
    public function call()
    {
        $app = $this->app;
        $paths = explode('/', $app->request()->getResourceUri());
        $locale = $paths[1];
        $currentUrl = '/'.join(array_slice($paths, 2), '/');
        $localeFile = $app->config('localePath') .'/'. $locale .'.yml';

        if(!file_exists($localeFile)) {

            if($locale != '') {

                try{
                    $app->notFound();
                } catch(Exception $e) {}

                return;
            }

            $preLocale = $app->getCookie('locale');
            $locale = $preLocale ? $preLocale : $app->config('defaultLocale');

            try{
                $app->redirect('/'.$locale);
            } catch(Exception $e) {}

            return;
        }

        $app->environment->offsetSet('PATH_INFO', $currentUrl);
        $app->setCookie('locale', $locale, mktime().time() + 60*60*24*100);
        $this->next->call();
    }
}
```

**Comment by piotr-cz** [comment]
Thanks @garyyeap, but besides pages with language prefix, I've create an API that's language agnostic. That's why I'd prefer to use groups, it's the cleanest solution.

**Comment by piotr-cz** [comment]
I wonder if this could go into 2.x release since here's the code and test are passing

**Comment by lalop** [comment]
I think this will not happen for Slim2 since there is no new features added to slim2

**Comment by piotr-cz** [comment]
Depends on the point of view. For me it's a bugfix ;)

**Comment by codeguy** [comment]
Re-assigning to @akrabat for review.

**Comment by akrabat** [comment]
Is the work against the master or against develop branch?

**Comment by piotr-cz** [comment]
Under the pull request descriptions it says `slimphp:develop`

**Comment by akrabat** [comment]
Yes, but the diff is against a class that's only in `master` …

**Comment by piotr-cz** [comment]
I'd say that the context of develop branch has changed since this PR. It was more like minor version develop (2.x) and now it's like major future version develop (3.x)

**Comment by garyyeap** [comment]
Is this getting merged? if does, I will send another PR for 3.x on this weekend

**Comment by akrabat** [comment]
@codeguy do you want this for Slim 2 or 3?

**Comment by codeguy** [comment]
Slim 2 is done. If we're going to pull this in, it'll be for 3 only.

**Comment by piotr-cz** [comment]
If Slim 3 will use [nikic/fast-route](https://github.com/nikic/FastRoute), similar PR won't be necessary as it's already built in there.

However Slim 2 (ATM only stable release) IMHO deserves having this fixed. But I won't bug anymore

**Pull request closed without merging**
