### PR TITLE
Improved CallableResolver's flow.

### PR DESCRIPTION
**Pull request by irfanevrens**

### CODE REVIEW

**Comment by silentworks** [comment]
What makes this an improvement over what was already there?

**Comment by irfanevrens** [comment]
I simplified function body and deleted some "else statements" and separate logics. I do not know why coverage decreased.

**Comment by akrabat** [comment]
Removing the else statements is nice, but I don't want it split into two methods. Please refactor so that it is back in the single `resolve` method.

**Comment by silentworks** [comment]
This is not an issue at the moment as this change doesn't give any performance increase or the likes and it will be refactored in next major version.

**Pull request closed without merging**
