### PR TITLE
Changing Travis CI distro to fix HHVM build

### PR DESCRIPTION
**Pull request by Sam-Burns**
In a similar vein to https://github.com/phpspec/phpspec/pull/1103.

### CODE REVIEW

**Comment by geggleto** [comment]
is there any way to just change it for HHVM or does it have to be global for all tests?

I suspect that the travis-ci dudes are going to run out of trusty servers at some point and builds will take longer.

**Comment by Sam-Burns** [comment]
No, it's a global setting.  The build time doesn't seem to be a problem.

**Comment by danopz** [comment]
Could you try following, I added a similar matrix into another package

```
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: hhvm
      dist: trusty
```

**Comment by akrabat** [comment]
What's the default distro?

**Comment by piotr-cz** [comment]
@akrabat It looks like it's _Ubuntu Precise,_ at least from details of this failed job: https://travis-ci.org/slimphp/Slim/jobs/242799904.

And in the config 
```
"dist": "precise",
"os": "linux"
```

**Comment by akrabat** [comment]
So probably better to be on trusty globally anyway

**Comment by Sam-Burns** [comment]
So should I leave it like this, or try the matrix thing?

**Comment by akrabat** [comment]
Global works for me.

**Comment by akrabat** [comment]
Can you raise the same thing against 4.x too please?

**Comment by piotr-cz** [comment]
Can I trigger tests somehow again on other PR?

**Comment by akrabat** [comment]
Rebase against latest `3.x` & `git push --force` the branch…

**Comment by piotr-cz** [comment]
thank you

**Pull request merged**
