### PR TITLE
Added support for custom router implementations to \Slim\Slim

### PR DESCRIPTION
**Pull request by elazar**
Applied changes from [this pull request](https://github.com/codeguy/Slim/pull/466) to the develop branch as requested.

### CODE REVIEW

**Comment by elazar** [comment]
Ah, I think I actually intended to change that constructor line to call out to `$this->router()` (to allow for subclasses to override the behavior). I'll try to get that fixed today. Thanks for the feedback. :)

**Comment by codeguy** [comment]
Slim will be getting an IoC container really soon which should make it super simple to define custom router and route objects immediately after app instantiation. This way you can simply instantiate your subclass inside of the router or route's Closure definition.

Thoughts?

**Comment by elazar** [comment]
@codeguy Any chance we could see some example code showing usage of this new feature as you've described it?

**Comment by codeguy** [comment]
Sure. You would define a custom Router for Slim to use like this:

```
<?php
$app = new \Slim\Slim();
$app->container->singleton('router', function ($c) {
    return new \My\Router();
});
// Define routes
$app->run();
```

This assumes that `\My\Router` implements the same interface as `\Slim\Router`, but I think that's a safe assumption to make.

**Comment by elazar** [comment]
I think I would codify that assumption with an actual interface:
1. Create an interface (e.g. `\Slim\RouterInterface`) with the same API as `\Slim\Router`
2. Have `\Slim\Router` explicitly implement that interface in its class definition
3. Change any existing typehint references to `\Slim\Router` in Slim to instead reference that interface

At that point, anything implementing the interface can be provided and PHP internals for checking interface implementation will provide helpful error messages if the interface implementation is flawed.

**Comment by codeguy** [comment]
I agree. Good point. But do you otherwise approve of my approach?

**Comment by elazar** [comment]
Otherwise, sure, this looks like a good approach.

**Comment by codeguy** [comment]
Closing in favor of https://github.com/codeguy/Slim/issues/398

**Pull request closed without merging**
