### PR TITLE
Fix prophecies

### LINKED ISSUE #2901: Not an issue, just a note - tests fail
PHPUnit seems to fail when using the currently newest `phpsec/prophecy` version 1.10.0.

See https://github.com/phpspec/prophecy/issues/457 and https://github.com/phpspec/prophecy/issues/458

### PR DESCRIPTION
**Pull request by adriansuter**
Fixes #2901.

### CODE REVIEW

**Comment by l0gicgate** [comment]
Should we update the composer file as well to `1.10`?

https://github.com/slimphp/Slim/blob/4.x/composer.json#L52

**Comment by adriansuter** [comment]
Sure, I don't think anyone will get hurt.

**Comment by froschdesign** [comment]
@adriansuter @l0gicgate 
First: great to see your quick reaction on this topic.
But so far it is not clear if it is a problem in Prophecy and / or a BC break. Maybe it would help if you joined the discussion to the [related issue report](https://github.com/phpspec/prophecy/issues/457). This could be helpful, also for others.

**Comment by adriansuter** [comment]
I just wrote to the corresponding issue https://github.com/phpspec/prophecy/issues/458. Let's see and wait.

In the meantime, how about updating `composer.json` into
```
        "phpspec/prophecy": ">1.8 <1.10",
```

**Comment by l0gicgate** [comment]
> "phpspec/prophecy": ">1.8 <1.10",

@adriansuter this is a good temporary solution. 

Using `Argument::is()` is also a good solution but it makes me worried about all the changes we have to do to all the other repos.

Thank you for the quick PR by the way. I think we should probably wait to merge this until we hear back on https://github.com/phpspec/prophecy/issues/457

**Comment by t0mmy742** [comment]
[phpspec/prophecy#460](https://github.com/phpspec/prophecy/pull/460) is going to resolve this issue.

But, as mentionned in the PR, it is a best practice to use Argument::is() for strict comparison.

It is maybe better for Slim to use Argument::is() (we don't have that much changes to do in other repos).

**Comment by l0gicgate** [comment]
Okay @t0mmy742 I'm going to merge this then.

**Pull request merged**
