### PR TITLE
Added query params support to nginx

### PR DESCRIPTION
**Pull request by hjr3**
The documentation for the nginx configuration did not send query parameters in
the URL to the calling code. This means something like /test?hello=world would
fail to set the $_GET superglobal with the 'hello' key.

### CODE REVIEW

**Comment by smagch** [comment]
+1
I'm currently doing exactly the same way in my `nginx.conf`. The first time I set up nginx, it takes a hour to solve this problem.

#55

**Comment by tyd** [comment]
+1 ... this got me the first time I used Slim with nginx. Using the same solution now.

**Comment by codeguy** [comment]
Please send all PRs to the develop branch.

**Comment by hjr3** [comment]
Opened #500

**Pull request closed without merging**
