### PR TITLE
Nginx Rewrite Rule

### PR DESCRIPTION
**Pull request by psx369**
Added a sample rewrite rule for nginx based servers.

### CODE REVIEW

**Comment by frolic** [comment]
It's better practice to use:

```
try_files $uri $uri/ /index.php?$query_string;
```

The [`try_files`](http://wiki.nginx.org/HttpCoreModule#try_files) directive can be used both in a `server` and `location` contexts, though most applications will put it in their `server` context.

**Comment by ryh** [comment]
how to skip the 'assets'  folder or  '.png'  files from routing ?
thanks

**Comment by frolic** [comment]
This will skip any existing files/directories.

**Comment by codeguy** [comment]
The develop and release-\* branches have had an nginx rewrite rule for a while. It will be available in master later this week once I take 1.6.0 live.

**Comment by smagch** [comment]
`/index.php?$query_string;` works perfectly on my environment. I have several `index.php` files.

```
index.php
+ api
  - index.php
+ v
  + dev
    - index.php
```

So I configured like following

```
location / {
    try_files $uri $uri/;
}

location /api {
    try_files $uri /api/index.php?$query_string;
}

location ~ \.php$ {
    include fastcgi.conf;
    fastcgi_pass   127.0.0.1:9000;
}
```

**Pull request closed without merging**
