### PR TITLE
#1386 fix

### PR DESCRIPTION
**Pull request by bota0mg**

### CODE REVIEW

**Comment by geggleto** [comment]
The one problem with this fix is that it reads the entire input stream into memory again... Given post_max sizes this is not ideal. However there does need to be a solution for this issue. We might need an additional wrapper around the current stream api implementation of php.

**Comment by bota0mg** [comment]
I'm afraid that I don't have either time and skills for that, at least not right now.

**Comment by geggleto** [comment]
That's no problem, thank you for letting us know!

**Comment by JoeBengalen** [comment]
Or look at phly:

https://github.com/phly/http/blob/master/src/PhpInputStream.php

He puts every read a cache property so it can be read again from there if needed.

**Pull request closed without merging**
