### PR TITLE
Fix error message, issue #2795

### PR DESCRIPTION
**Pull request by QinisoM**
This is an update to the error message as reported

### CODE REVIEW

**Review by l0gicgate — COMMENTED** [review]
I think we need to add wording along the lines of “in the browser/client”. That’s what we’re trying to convey. I don’t know how to word it properly but:

To see the error details from your browser/client set “displayErrorDetails” to “true” in the ErrorHandler’s constructor. 


🆘 not an English major. Send help.

**Comment by RyanNerd** [comment]
In Slim 3.x this is what the [verbiage looks like](https://github.com/slimphp/Slim/blob/200c6143f15baa477601879b64ab2326847aac0b/Slim/Handlers/AbstractError.php#L48):
 `$message .= PHP_EOL . 'View in rendered output by enabling the "displayErrorDetails" setting.' . PHP_EOL;`

@l0gicgate Once it is decided how this should be worded in 4.x should 3.x also be changed to the same or would that be a b/c?

**Comment by l0gicgate** [comment]
We can leave it for Slim 3 since it is long-standing and it’s an actual app setting.

**Comment by odan** [comment]
The response must always be the same. It should be irrelevant on which operating system the error message is created. We should keep `\n` and never use `PHP_EOL` in this context. Thanks.

**Comment by l0gicgate** [comment]
We need to discuss further in #2795 before PRs are raised. Follow there

**Pull request closed without merging**
