### PR TITLE
move back app:responded

### PR DESCRIPTION
**Pull request by lalop**
Move back responded status as class property for testing purpose

### CODE REVIEW

**Comment by akrabat** [comment]
I don't understand this PR. The `testRunSendBody` test works with the current code.

**Comment by lalop** [comment]
It works because we have removed `testHaltInMiddleware`, but if we have two tests that does an `$app->run()` the second one will fail.

**Comment by akrabat** [comment]
If we remove responded completely, then two tests will work…

**Comment by lalop** [comment]
In both case the `responded` defined as static in the method isn't the good option

**Comment by akrabat** [comment]
I agree. I'm just wondering if we can lose it completely.
@codeguy said that it was needed due to headers being sent, but I can't see why that's the case as we have a `headers_sent` check.

**Comment by lalop** [comment]
It's what I see while rebasing.
I think we can removed it completely.
Do you want me to update this pr in this way ?

**Comment by akrabat** [comment]
That's my gut feeling. We'll wait on @codeguy though.

**Comment by akrabat** [comment]
As @codeguy never followed up, let's remove `$responded`.

**Comment by codeguy** [comment]
If it can be removed without consequences go for it.

**Comment by akrabat** [comment]
Please reopen against the `3.x` branch when ready.

**Pull request closed without merging**
