### PR TITLE
Implements Mobile_Detect lib for Response's write

### PR DESCRIPTION
**Pull request by zguillez**
Allow different write responses for calls from **Desktop** or **Mobile** (phone, tablet, iOS and Android):
$response->write("All devices");
$response->writeDesktop("Only from desktop");
$response->writeMobile("Only from mobile");
$response->writePhone("Only from a phone");
$response->writeTablet("Only from a tablet");
$response->writeIOS("Only from iOS");
$response->writeAndroid("Only from Android");

### CODE REVIEW

**Comment by akrabat** [comment]
I'm not sure that this is a core Slim functionality.

**Comment by geggleto** [comment]
This should be in its own composer project.

**Comment by tuupola** [comment]
I like the feature but it does not belong to core.

**Comment by akrabat** [comment]
Not a core feature.

**Pull request closed without merging**
