### PR TITLE
Return Http\Response from App::redirect

### LINKED ISSUE #1107: Return Http\Response from App::redirect
The redirect helper is nice but wouldn't it be better to do this:

```
return $app->redirect('/page');
```

instead of the current:

```
$app->redirect('/page');
```

The current implementation relies on `App::stop` and exceptions but this proposal makes the control flow much clearer. For example [Silex](http://silex.sensiolabs.org/doc/usage.html#redirects) already does this.

### PR DESCRIPTION
**Pull request by siiptuo**
Resolves #1107 but raises questions about similiar behavior in `App::halt`. Will `App::stop` be needed?

### CODE REVIEW

**Comment by JoeBengalen** [comment]
On line 375 of App.php there is a typo. It returns the Response, its not throwing.

**Comment by siiptuo** [comment]
@JoeBengalen oh no... thanks for noticing it!

**Comment by JoeBengalen** [comment]
The difference in behaviour of returning and throwing an Exception is if the middleware stack gets called or not. On returning if will travel all the way down and up the stack. On throwing the Exception it will not and go straight to `App::run()`.

I think returning will be fine, but the difference should be considered. My vote will be returning, as I never liked the way an Exception was used to stop the application heren.

**Comment by codeguy** [comment]
I do want to maintain a way to short-circuit the middleware stack and exit _immediately_, which is what stop currently does.

**Comment by siiptuo** [comment]
So should the short-circuit also apply to `redirect`? Or only `halt` and `stop`? In point of view of the user hiding the throw exception can be misleading. Is there any way to combine these two approaches?

**Comment by codeguy** [comment]
For now let's leave `halt()` and `stop()` as they are. Let's modify only the `redirect()` method.

**Pull request merged**
