### PR TITLE
adds redirectTo method

### PR DESCRIPTION
**Pull request by maldoinc**
Adds method `redirectTo` which is a shortcut for `redirect(urlfor(..))`

Helps making the code more readable by encapsulating a common pattern.

### CODE REVIEW

**Comment by designermonkey** [comment]
:+1:

**Comment by DavidePastore** [comment]
:+1:

**Comment by lrlopez** [comment]
I find this really useful. Thanks for the PR!

**Comment by ecoreng** [comment]
:+1:

**Pull request merged**
