### PR TITLE
Only instantiate the controller class if the route is requested

### PR DESCRIPTION
**Pull request by ciaranmaher**
Not sure if this is a document error or a bug but according to the [2.40 release notes](https://github.com/codeguy/Slim/releases/tag/2.4.0) the app will instantiate the controller class when the route is requested.

This is not the case, presently the class is instantiated even if the route is not requested. 
e.g. 
$app->get('/hello/:name', '\Hello:sayHello');
$app->get('/bye/:name', '\GoodBye:sayBye');

If you request `/hello/Josh`, the constructor of both `\Hello` and `\GoodBye` will be triggered. 

To get around this issue I've just moved the instantiation of the class from `setCallable` to `getCallable`

### CODE REVIEW

**Comment by calmdev** [comment]
I can reproduce this on 2.4.0 as well.

**Comment by codeguy** [comment]
Thanks. Will merge into a point release soon.

**Comment by lectrotext** [comment]
Bump. When's this getting into a point release?

**Comment by codeguy** [comment]
Forgot about this for 2.4.2. Will roll this out in 2.4.3 soon.

**Comment by danielgsims** [comment]
Awesome. This will help out a lot.

**Comment by mcuelenaere** [comment]
Similar to #721

**Comment by mcuelenaere** [comment]
What if a user calls `$route->setCallable([new Foo, 'bar']);` ?

**Comment by codeguy** [comment]
Closing in favor of #721

**Pull request closed without merging**
