### PR TITLE
fix: compatibility of php8.1 for slim3

### PR DESCRIPTION
**Pull request by everyx**
function `explod` and `preg_replace_callback`

`PHP message: PHP Deprecated:  xxxx(): Passing null to parameter #n ($xxx) of type xxx is deprecated /.../vendor/slim/slim/Slim/.../xxx.php on line nnn`

See: https://www.php.net/manual/en/migration81.deprecated.php

### CODE REVIEW

**Comment by everyx** [comment]
@l0gicgate Can we disable `phpunit` with php8 for slim3? The `phpunit` that `slim3` depends on is not compatible with php8, I just want to make my slim3 application can continue to run under php8.1

**Comment by everyx** [comment]
@l0gicgate I just disable phpunit test in `matrix.php >= 8` and pull request target branch or pushed branch is `3.x` in `tests.yml`

**Comment by l0gicgate** [comment]
We are not doing any more releases besides security fixes to Slim 3. It's a rabbit hole to try and make this happen.

**Comment by everyx** [comment]
> We are not doing any more releases besides security fixes to Slim 3. It's a rabbit hole to try and make this happen.

Ok, I will maintain in my own fork, thank you, close this PR

**Pull request closed without merging**
