### PR TITLE
Refer to $app as $this inside a router

### PR DESCRIPTION
**Pull request by IlanFrumer**
### Instead of repeating the keyword use everywhere like that....

``` php
$app = new \Slim\Slim();

$app->get('/',function ()  use ($app) {

});

$app->group('/api',function ()  use ($app) {

    $app->get('/',function ()  use ($app) {

    });

});
```
### We can just use $this:

``` php
$app = new \Slim\Slim();

$app->get('/',function () {

});

$app->group('/api',function ()  {

    $this->get('/',function ()  {
          $this->halt(404);
    });

});
```

### CODE REVIEW

**Comment by tuupola** [comment]
:+1:

**Comment by erizocosmico** [comment]
It would be great to be able to do that but according to travis the method bindTo does not exist https://travis-ci.org/codeguy/Slim/jobs/13025874 (it was added in php 5.4). The tests also fail for 5.4.

**Comment by IlanFrumer** [comment]
bindTo would only work if you have php > 5.4

**Comment by tuupola** [comment]
I think Slim follows [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#5-control-structures) so you should include braces around control structures.

**Comment by petarov** [comment]
This is a nice feature! But I would pull against the `develop` branch because tests obviously need be adapted too. There are also a lot of changes in `develop` and maybe Slim system reqs would also change to >= 5.4 in next major release

**Comment by IlanFrumer** [comment]
[a pull against the develop branch](https://github.com/codeguy/Slim/pull/661)

Thanks a lot

**Pull request closed without merging**
