### PR TITLE
Allow underscores in method names for controllers

### PR DESCRIPTION
**Pull request by hischeapmoves**
This adds an underscore to the regex used to compose the $callable variable to match cases where the method name contains an underscore.

### CODE REVIEW

**Comment by calmdev** [comment]
I can also reproduce this on 2.4.0 and can confirm that the PR resolves it.

**Comment by davestewart** [comment]
This would be useful, esp for post routes, i.e. function add_post()

**Comment by mcuelenaere** [comment]
Similar to #718

**Comment by codeguy** [comment]
Closing in favor of https://github.com/codeguy/Slim/pull/718

**Pull request closed without merging**
