### PR TITLE
Update .htaccess to support existing directories

### PR DESCRIPTION
**Pull request by cpl-repo**
With this option, not just existing files are skipped but existing directories as well.

### CODE REVIEW

**Comment by tuupola** [comment]
:+1: This is what I am using myself too.

**Comment by StJudeWasHere** [comment]
:+1: I like this too.

**Comment by ffflabs** [comment]
Just to be on the safe side, I suggest skipping symlinks as well

```
RewriteCond %{REQUEST_FILENAME} !-l
```

**Comment by brandisher** [comment]
:+1:

**Pull request merged**
