### PR TITLE
Added a new handler strategy named RequestResponseSI

### PR DESCRIPTION
**Pull request by irfanevrens**
Using this strategy allow us to not write request and response parameters in every callable functions. I used the "Setter Injection" method.

### CODE REVIEW

**Comment by akrabat** [comment]
You should provide this as a separate component.

**Comment by codeguy** [comment]
Agreed.

**Comment by irfanevrens** [comment]
I am using this as handler on a production app. Is component mean middleware? How can I implement it, any example or docs?

**Comment by akrabat** [comment]
Just put it in it's own repo with a composer.json set up with autoloading and a readme to show how to set it up.

**Pull request closed without merging**
