### PR TITLE
Improving test coverage

### PR DESCRIPTION
**Pull request by gabriel403**
Improving test coverage

### CODE REVIEW

**Comment by gabriel403** [comment]
Some phpunit idiosyncrasies 

With `--process-isolation`

```
Lines:   85.67% (1022/1193)
```

Without

```
Lines:   84.58% (1009/1193)
```

If anyone has any thoughts what I need to fix for this, glad to hear them!

**Comment by geggleto** [comment]
a test for App:Run i have not been able to get to it.

**Comment by akrabat** [comment]
is this ready to merge?

**Comment by gabriel403** [comment]
@akrabat i'm quite happy for this to merge and i'll open up further PRs as I create more

**Pull request merged**
