### PR TITLE
Fixes flash messaging/SessionCookie decoding failure when cookies.encrypt = true

### PR DESCRIPTION
**Pull request by jeremykendall**
Without a way to check if a cookie is already encoded, `\Slim\Http\Util::serializeCookies()` will encode an already encoded cookie. This is an issue when `\Slim\Middleware\SessionCookie` sets an encoded cookie value on the response object during `\Slim\Middleware\SessionCookie::saveSession()` (as `\Slim\Http\Util::serializeCookies()` will encode every cookie it gets if `cookies.encrypt` = `true`).  Since the cookie is only decoded once during `\Slim\Middleware\SessionCookie::loadSession()`, the cookie's actual decoded value is never available to the application, and `unserialize()` in `\Slim\Middleware\SessionCookie::loadSession()` will fail.

This PR adds the ability to tell `\Slim\Http\Util::serializeCookies()` to skip encoding a cookie during the serialization process.

### CODE REVIEW

**Comment by codeguy** [comment]
I'm wondering if a simpler solution is to simply not encrypt cookie values in the `\Slim\Middleware\SessionCookie` class and let Slim handle cookie encryption as it does already. What are your thoughts?

**Comment by jeremykendall** [comment]
@codeguy :+1: 

That would also take care of the weirdness of having two sets of cookie settings, one global (except for `SessionCookie`) and one just for `SessionCookie`.

**Comment by codeguy** [comment]
Cool. Feel free to update this PR or close and submit a new one and I'll get it pulled into 2.3.2 to be released soon.

**Comment by jeremykendall** [comment]
Sounds good.  Thanks!

**Comment by jeremykendall** [comment]
@codeguy I'm going to create a new PR for simplicities sake, but it looks like the develop branch `SessionCookie` class no longer exists.  Where should I branch from and submit a PR against?

**Comment by codeguy** [comment]
Submit a PR to the 2.3.2 release branch. This class will be removed from the next major release and replaced by the new Session class. But this change is still very important for apps using the 2.\* codebase.

**Comment by jeremykendall** [comment]
Sounds good.  Thanks for the update.

**Comment by jeremykendall** [comment]
Superseded by #635.

**Pull request closed without merging**
