### PR TITLE
Update PrettyExceptions.php

### PR DESCRIPTION
**Pull request by hardlynoticeable**
The str_replace function was not terminating lines in the trace because the newline was enclosed in single quotes and not double quotes.  I also formatted the returned HTML slightly and added DOCTYPE.

### CODE REVIEW

**Comment by tuupola** [comment]
Non patch related question. What git client are you using? I have been trying to find out which client makes the default "Update filename.txt" commit messages.

**Comment by StJudeWasHere** [comment]
This was fixed in PR #879. I didn't change the doctype though.

**Comment by hardlynoticeable** [comment]
I didn't.  I used Github's web based interface.  Actually I don't use
github often and I found their interface a little confusing.

Stephen J Akins
https://google.com/+StephenAkins/about

**Comment by hardlynoticeable** [comment]
I had another change immediately afterwards that I may not have pushed
properly...  I added an extra newline so the last div in the trace closed
properly and I made a bunch of little formatting changes including taking
out the PRE tags as they weren't needed any longer....  Did you see those
changes also?  Just wondering.

Stephen J Akins
https://google.com/+StephenAkins/about

**Comment by silentworks** [comment]
Fixed and merged fe1c215.

**Pull request closed without merging**
