### PR TITLE
#1836 count amount of bytes read instead of chunks

### PR DESCRIPTION
**Pull request by llvdl**

### CODE REVIEW

**Comment by llvdl** [comment]
This is a fix for #1836 where not all data is read if `StreamInterface::read` returns less than the request amount of bytes.

**Comment by akrabat** [comment]
Unit tests fail in [testRespondWithPaddedStreamFilterOutput](https://github.com/slimphp/Slim/blob/3.x/tests/AppTest.php#L1520).

**Comment by akrabat** [comment]
Suggested fix:

``` diff
diff --git a/Slim/App.php b/Slim/App.php
index cd478f1..e65c6e4 100644
--- a/Slim/App.php
+++ b/Slim/App.php
@@ -386,6 +386,9 @@ class App
             if (isset($contentLength)) {
                 $amountToRead = $contentLength;
                 while ($amountToRead > 0 && !$body->eof()) {
+                    if ($amountToRead < $chunkSize) {
+                        $chunkSize = $amountToRead;
+                    }
                     $data = $body->read($chunkSize);
                     echo $data;

```

**Comment by llvdl** [comment]
The unit tests run without problems on my local environment (Xubuntu 15.10, PHP 5.6.11), but fail on Travis. 

If you could help me reproduce the failing test locally, then I would appreciat it. I can probably get on IRC tonigh (CET).

**Comment by akrabat** [comment]
You need to install the `mcrypt` PHP extension locally as the test that's failing only runs if that's installed.

**Comment by llvdl** [comment]
Thanks!

**Comment by llvdl** [comment]
Hmm.. installed php5-mcrypt, but the test still succeeds.

**Comment by akrabat** [comment]
Can you see `mcrypt` in the list when you run `php -m` ?

**Comment by llvdl** [comment]
`mcrypt` does not show up, I will investigate why.

The fix you suggested seems to do the trick! Thanks for looking into this.

**Comment by akrabat** [comment]
Thanks!

**Pull request merged**
