### PR TITLE
Made it wurst. #WurstCon

### PR DESCRIPTION
**Pull request by SammyK**
Self explanatory. This is not a troll PR. All tests pass. Requires mustard to run. #WurstCon

### CODE REVIEW

**Comment by mfrost503** [comment]
:+1:

**Comment by jmikola** [comment]
:+1:

**Comment by dcousineau** [comment]
:+1:

**Comment by dragonmantank** [comment]
:+1:

**Comment by philsturgeon** [comment]
:+1:

**Comment by joshmanders** [comment]
:+1:

**Comment by SammyK** [comment]
:+1:

**Comment by codeguy** [comment]
Closing due to lack of relish.

**Comment by Ocramius** [comment]
There's not enough wurst in this PR. Where's the variety?!

**Comment by corykeane** [comment]
remember, no ketchup

**Comment by matthewbaggett** [comment]
This is the Worst Wurst. I miss Burgermeister Q_Q

**Comment by tw2113** [comment]
How dare you hold the mustard!

**Comment by philsturgeon** [comment]
LOCK IT DOWN HELP

-- 
Phil Sturgeon

I talk about turtles, bikes and code over here philsturgeon.uk

**Pull request closed without merging**
