### PR TITLE
add `psr/http-message-implementation` to composer

### PR DESCRIPTION
**Pull request by lalop**
Define `psr/http-message-implementation` as provided by Slim

### CODE REVIEW

**Comment by akrabat** [comment]
I'm not sure we should do this as Slim is more than just a PSR 7 implementation.

This would make more sense when we have a viable `Slim\Http` repo I think?

**Comment by lalop** [comment]
This is usefull for composer, if a package need `psr/http-message-implementation` compoesr will ask to add a dependencie to complete the requirement

**Comment by akrabat** [comment]
Yes. I'm just not sure that Slim 3 is the right answer to that question.

**Comment by lalop** [comment]
Here is a list of librairy requiring `psr/http-message-implementation`  https://packagist.org/packages/psr/http-message-implementation/dependents

To use them with Slim we will need to install another implementation since Slim doesn't declare itself as providing it.

**Comment by akrabat** [comment]
Aha! I understand now.

**Pull request merged**
