### PR TITLE
Pass through 'templates.path' to view object singleton.

### PR DESCRIPTION
**Pull request by ziadoz**
Fixes `Slim\View` object not getting the correct 'templates.path' setting.

### CODE REVIEW

**Comment by ziadoz** [comment]
Should I remove the `$app->view->setTemplatesDirectory()` line in the `$app->render()` method? It seems like it's redundant now, as either the DI container or `$app->view()` will set the correct templates path on any custom view objects.

**Comment by codeguy** [comment]
@ziadoz Yes, you can remove the redundant call in the `render` method.

**Comment by ziadoz** [comment]
Okay, I've done that, along with a horrible rebase that appears to have added more commits…

**Comment by codeguy** [comment]
haha. That's fine I can cherry pick the relevant ones. Will do that today.

**Comment by codeguy** [comment]
Merged into https://github.com/codeguy/Slim/commits/release-2.3.6

**Pull request closed without merging**
