### PR TITLE
Http changes

### PR DESCRIPTION
**Pull request by designermonkey**
There's me thinking I can just keep adding to my PR, and you've pulled it already!

Anyway, here's a couple more changes for the last lot of Http classes work.

### CODE REVIEW

**Comment by designermonkey** [comment]
I notice there's no test for sub-requests yet. I would give it a go, but I'm not entirely sure how it is intended to work yet.

**Comment by designermonkey** [comment]
Something's gone weird with this branch, as some work is duplicated. Going to use a fresh branch and re-submit.

**Comment by codeguy** [comment]
haha. Sorry. I thought it looked fairly complete. If you want to keep working on a PR, just make a note of it in the initial comment so I don't pull it in too early :)

**Comment by designermonkey** [comment]
no probs :D

**Pull request closed without merging**
