### PR TITLE
Constructor params

### PR DESCRIPTION
**Pull request by danielgsims**
Allows setting construction parameters for Controller Classes discussed in issue #748 and PR #755. Expands on the work of @ciaranmaher in #739

### CODE REVIEW

**Comment by danielgsims** [comment]
@codeguy Any feedback Josh?

**Comment by danielgsims** [comment]
#739 was closed in favor of #721. I will look at redeveloping this with #721.

**Comment by 4nd** [comment]
Is this still under development? I know its been discussed before, but some way of getting the App instance into the controller, aside from as a route parameter, is pretty important.

I'm happy to take a look at it if nobody else is.

**Comment by danielgsims** [comment]
I was hoping for more feedback!

**Comment by 4nd** [comment]
How do we push this forward, am I missing something?  Is there some way in my controller to access the Slim instance, or its view without this functionality?

**Comment by danielgsims** [comment]
I canned this because there were two different solutions to Lazy Loading of Controllers: #721 and #739. #721 fixes this by creating a callable closure at the time of Route construction. #739 fixes this by only creating the controller when it was called. The way #739 went about this allowed me to create a setParams method to create a list of dependencies that could be used when the controller was constructed. However, since #721 created the callable immediately, there would be no time to handle a setParams method. I'm reviewing the code now, and there doesn't seem to be an immediately identifiable solution to me with this code review. I have some ideas brewing, however they require more heavy lifting than this solution which is no longer applicable :(

**Comment by danielgsims** [comment]
I created an alternative solution in #822

**Pull request closed without merging**
