### PR TITLE
Reopend Callback middleware

### PR DESCRIPTION
**Pull request by kanellov**
Hello,
I'm opening a new PR (previous #1103) against master branch, instead develop, since it's use is  for Slim 3.
I have created a middleware class for **Slim 2** that uses a callable in its call method. I have been using it for a while in my projects with Slim and I think it's very handy, especially in prototypes. Here's an example

``` php
<?php

$app = new Slim\Slim();
$app->add(new Slim\Middleware\Callback(function ($app, $next) {
    // do some work ...
    // call next middleware
   $next->call(); 
   // do some extra work ...
});
```

### CODE REVIEW

**Comment by JoeBengalen** [comment]
Maybe Im missing somehting, but Slim 3 middleware MUST be a callable. What does this `Middleware\Callback` improve?

http://docs-new.slimframework.com/concepts/middleware/

**Comment by codeguy** [comment]
Master branch is not accepting new features.

**Comment by kanellov** [comment]
@JoeBengalen this class is intended for Slim 2 version. @codeguy is the development of ver 2 frozen? If you are interested in this feature, could you tell from where to start my branch in order to merge right?
Thanks.

**Comment by JoeBengalen** [comment]
Ah I see. There's a type in the OP then. It says its intended for Slim **3**

**Comment by codeguy** [comment]
v2 is frozen except for security fixes.

**Comment by kanellov** [comment]
ok thanks

**Pull request closed without merging**
