### PR TITLE
release-2.4.1 Detect circular middleware stacks

### PR DESCRIPTION
**Pull request by marcioAlmada**
ported #706 to 2.4.1 codebase.

### CODE REVIEW

**Comment by marcioAlmada** [comment]
@codeguy, finally I had some time for this, ready for 2.4.1.

**Comment by marcioAlmada** [comment]
It seems travis building is failing on hhvm runtime (errors are not related to this pull request).

**Comment by codeguy** [comment]
Yep I'm aware of that. I'll remove hhvm testing until Travis CI can release a new image including the latest hhvm bug fixes.

**Comment by marcioAlmada** [comment]
You can also use this configuration to test against hhvm runtime but allowing erros:

``` yml
matrix:
  allow_failures:
    - php: hhvm
```

**Pull request merged**
