### PR TITLE
Add helper function to retrieve accept headers if available

### PR DESCRIPTION
**Pull request by gabriel403**
Simplifies the ability to retrieve accept headers, helpful in those situation where `X-Requested-With` is missing and thus the `isAjax` function doesn't respond correctly as then we can check for `application/json` in the accept headers.

### CODE REVIEW

**Comment by akrabat** [comment]
Can you explain why we need this?

**Comment by gabriel403** [comment]
@akrabat I added a description, hope that'll help.

**Comment by akrabat** [comment]
I think I'd rather have a method that returns true if a given mime-type is in the list of accept headers.

What do others think?

(ping @codeguy, @silentworks, et al)

**Comment by akrabat** [comment]
Please reopen against the `3.x` branch when ready.

**Comment by gabriel403** [comment]
@akrabat OK that sounds reasonable, `hasAcceptHeader`

**Pull request closed without merging**
