### PR TITLE
Fix example in README

### PR DESCRIPTION
**Pull request by mnapoli**
Am I missing something or is the example wrong? I think it's a PSR-7 response so the `write()` method exists on the body only.

### CODE REVIEW

**Comment by tflight** [comment]
Slim's response object does have a convenience method for `write`, [seen here](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Response.php#L280). So the example does work, but doesn't conform to PSR-7. Therefore you couldn't swap out Slim's response with another PSR-7 response with the existing example and your example would be needed.

**Comment by mnapoli** [comment]
Mmh OK, I was confused since this is also not consistent with https://www.slimframework.com/

Anyway thanks!

**Comment by tflight** [comment]
I don't disagree with you though. We probably should be using PSR-7 compatible examples whenever possible and at least those two examples should be consistent.

**Comment by tflight** [comment]
@mnapoli reading my response again, it might not be clear what i was trying to say. I think your PR is valid and is better than the existing example.

**Comment by mnapoli** [comment]
Reopening in case you want to merge it, feel free to close it again if it's not necessary :)

**Comment by akrabat** [comment]
Thanks @mnapoli

**Pull request merged**
