### PR TITLE
Make http methods case insensitive. Convert to uppercase

### LINKED ISSUE #1580: Slim3 map is case sensitive
Now map is case sensitive `$app->map(['GET', 'POST']` != `$app->map(['get', 'post']`
Maybe it could be insensitive?

### PR DESCRIPTION
**Pull request by dopesong**
Close #1580

### CODE REVIEW

**Comment by geggleto** [comment]
:+1: meh we discussed this in IRC it, I approve of keeping it simple.

**Comment by silentworks** [comment]
Will get this merged as soon as we decide on what the next milestone will be.

**Comment by akrabat** [comment]
If this is all we have, I'm minded to go with a 3.0 final. Thoughts?

**Comment by geggleto** [comment]
I want to write up more stuff regarding the getIp() debacle. It actually broke my production environment, and I need to come up with a good way to do it.

**Pull request merged**
