### PR TITLE
Container

### PR DESCRIPTION
**Pull request by designermonkey**
The only issue I see here may be the code on line 193. I don't know what passing `$this` into a property of itself as a container will do.

As mentioned on the issue tracker, I can't get the tests to run, which is probably my lack of understanding on that front. They complain that `Slim\Helper\Set` is not found:

```
PHP Fatal error:  Class 'Slim\Helper\Set' not found in /Users/designermonkey/Projects/Slim/Slim/Slim/Slim.php on line 52
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar:531
PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar/PHPUnit/TextUI/Command.php:138
PHP   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar/PHPUnit/TextUI/Command.php:606
PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar/PHPUnit/TextUI/Command.php:778
PHP   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar/PHPUnit/Util/Fileloader.php:76
PHP   8. include_once() phar:///usr/local/Cellar/phpunit/3.7.22/libexec/phpunit-3.7.22.phar/PHPUnit/Util/Fileloader.php:92
PHP   9. require_once() /Users/designermonkey/Projects/Slim/Slim/tests/bootstrap.php:4
```

If you can find the problem there, let me know and I'll ensure this is fully tested before it's pulled.

### CODE REVIEW

**Comment by designermonkey** [comment]
This will teach me to code at 1am. The `get` method already exists on the `Slim` class, and therefore throws an error.

**Comment by silentworks** [comment]
What was the end result of this? did it work?

**Comment by codeguy** [comment]
I'm going to hold off on this and go ahead and roll out 2.3.2 later today or tomorrow morning. If you want to get a working PR in soon I can include it in the 3.0 release.

**Comment by designermonkey** [comment]
To get a working PR and maintain the http method functions, the method names in the container need to change, as `get` clashes with the http method function `get`.

**Comment by designermonkey** [comment]
Other than that, I think it's good to go... But I need to test it.

**Pull request closed without merging**
