### PR TITLE
solve variable name conflict problem in View

### PR DESCRIPTION
**Pull request by williamwa**
currently, when we set 'template' or 'templatePath' to view, it will conflict with the function's local variables.
my change fixed this problem.

### CODE REVIEW

**Comment by williamwa** [comment]
Hi,

My change mainly fix this problem: try doing this in your code:

$app->render('css.php',array('template'=>'abc'));

the $template in the css.php file, is 'css.php' not 'abc'

thanks

**Comment by codeguy** [comment]
Right. I understand that you are now able to use your own `template` View variable... however, you disabled the ability to invoke `View::render` independent of `View::display`. If you want to revert this one regression in your push request, I'll be happy to pull it in.

Best,
Josh

**Comment by williamwa** [comment]
Hi, please check this new commit, it add a method: fetch to solved the problem.

**Comment by codeguy** [comment]
Thanks! Looks good. Pulling this into release-1.6.3 now.

**Comment by fatmuemoo** [comment]
Why is templatePath deprecated?

**Pull request closed without merging**
