### PR TITLE
Adding Cors support

### PR DESCRIPTION
**Pull request by geggleto**
Related to #1851

### CODE REVIEW

**Comment by geggleto** [comment]
This will add the ability to pull from the router the HTTP Verbs associated with a given pattern.

Patterns can be retrieved from a Request Object in a middleare when the `determineRouteBeforeAppMiddleware` setting is set to `true`.

This then will lead to the ability to use a middleware to accurately provide CORS Support.

``` php
///....

$app->add(function ($req, $res, $next) {
    $route = $req->getAttribute('route');
    $router = $this->router;

    $verbs = $router->getMethods($route->getPattern());

   $res = $next($req, $res);

   $res->withHeader('Access-Control-Allow-Methods', implode(',', $verbs))
         ->withHeader('Access-Control-Allow-Origin', '*');

    return $res;
});


```

**Comment by dopesong** [comment]
In my opinion - there is no point for class like this. There could be two options:
- Add this functionality to main router.
- Move it into separate repo as extension.

Also your example is lack of information how it should be used, because right now you need to change default router - what adds additional complexity.

**Comment by geggleto** [comment]
I don't think a separate repo is the proper place.

The example to use it is trivial...
`
$container['router'] = function ($c) {
     return new CorsRouter();
};
`

**Comment by tuupola** [comment]
I also think this functionality belongs to main router.

**Comment by tuupola** [comment]
I found a way for middleware to get the defined verbs for current routes **pattern** with the code below.  This works currently without any changes to the router. Note that this is not always the the same as all the defined verbs for current routes **uri**. However it is close enough for most use cases.

``` php
require __DIR__ . "/vendor/autoload.php";

$app = new Slim\App([
    "settings"  => [
        "determineRouteBeforeAppMiddleware" => true,
    ]
]);

$app->add(function($request, $response, $next) {
    $pattern = $request->getAttribute("route")->getPattern();

    $methods = [];
    foreach ($this->router->getRoutes() as $route) {
        if ($pattern === $route->getPattern()) {
            $methods = array_merge_recursive($methods, $route->getMethods());
        }
    }

    $response = $response->write(print_r($methods, true));
    return $next($request, $response);
});

$app->get("/api/{id}", function($request, $response, $arguments) {
});

$app->post("/api/{id}", function($request, $response, $arguments) {
});

$app->map(["DELETE", "PATCH"], "/api/{id}", function($request, $response, $arguments) {
});

$app->run();
```

```
%curl --include http://localhost:8080/api/xxx
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Content-Length: 76

Array
(
    [0] => GET
    [1] => POST
    [2] => DELETE
    [3] => PATCH
)
```

**Comment by geggleto** [comment]
very cool @tuupola that should go into some sort of service provider then, and we can close this PR

**Comment by akrabat** [comment]
So we just need some middleware?

**Comment by dopesong** [comment]
Correct

**Comment by dopesong** [comment]
@tuupola have you checked how it works with routes groups?

**Comment by tuupola** [comment]
Just tested and seems to work.

**Comment by akrabat** [comment]
Closing as solution is possible without this change.

**Pull request closed without merging**
