### PR TITLE
always merge settings if 1st parameter is an array

### PR DESCRIPTION
**Pull request by pine3ree**
- avoids accidental assignments when $name in an array and num parameters > 1 
- avoids usage of magic methods

### CODE REVIEW

**Comment by codeguy** [comment]
Can you provide unit tests for the new recursive merge feature?

**Comment by pine3ree** [comment]
Hello,

i added a test. There seems to be an issue with travis build with php 5.5 in this test:
SlimTest::testExpiresAsString

kind regards

**Comment by tuupola** [comment]
Looks like timing issue in tests.

**Comment by pine3ree** [comment]
yeah, 
that test is so trivial.

**Comment by codeguy** [comment]
Merged into release-2.4.3. Thanks!

**Pull request closed without merging**
