### PR TITLE
Remove codeCoverageIgnore annotations

### PR DESCRIPTION
**Pull request by amad**
As they are considered as bad habit!

### CODE REVIEW

**Comment by akrabat** [comment]
They are there for a reason: the code coverage is run in PHP5.6, so that code is never run…

**Comment by amad** [comment]
I take your point about why added. But is it still the case? Because coverage report generated.

**Comment by akrabat** [comment]
Yes - see that the coverage dropped? That's because of this: https://coveralls.io/builds/8878310/source?filename=Slim%2FRoute.php#L347

**Comment by amad** [comment]
Fair enough :+1:
IMO I don't see difference between ignoring and leaving. either way is not green on this report.

But of course it's not big deal at all and I just send it because I didn't realize the reason behind it in the first place.
Thanks

**Comment by akrabat** [comment]
Thanks for looking at it.

The difference for me is that we've noted that it's intentional.

**Pull request closed without merging**
