### PR TITLE
Added pragmatic example in code example into README.md

### PR DESCRIPTION
**Pull request by ghost**
Added pragmatic example in code example into README.md

### CODE REVIEW

**Comment by akrabat** [comment]
Can you explain the reasoning behind this change?

**Comment by ghost** [comment]
Hi,
I was asking myself, why should we use two statements for doing something that can be done in one? At least in the example.
It’s going to be a lean example to show, on how simple and straightforward is, to use (setting up the Hello World) Slim, isn't it? Compared to other PHP micro frameworks, it looks like we have to do extra work to return a response. Why using more code than what is actually needed?
I understand that in the way you used in principle, it's clear for beginners, that the closure should always returns a valid Response, but that’s also clear from the well done documentation Slim has. I hope it’s not a stupid argument. WDYT? :)

**Comment by ghost** [comment]
@akrabat makes sense? :)

**Review by akrabat — APPROVED** [review]

**Comment by akrabat** [comment]
Yes. I understand your logic.

**Pull request merged**
