### PR TITLE
Added an optional default value to request->params()

### PR DESCRIPTION
**Pull request by erizocosmico**
This adresses issue #699.

``` php
$app->request->params('myfancyparam', 'my default value');
```

### CODE REVIEW

**Comment by codeguy** [comment]
Can you provide a unit test with this?

**Comment by erizocosmico** [comment]
Woah, sorry, I completely forgot about that. Can you reopen the PR? I'd provide an unit test with this right now.

**Comment by codeguy** [comment]
Didn't intend to close this. I believe this was auto-closed by GitHub when the target branch was removed :( Not seeing a button to re-open. Are you able to easily re-submit a new PR?

**Comment by erizocosmico** [comment]
Yep, I'll re-submit a new PR in a few minutes.

**Pull request closed without merging**
