### PR TITLE
Move valid protocol versions to a class static var

### PR DESCRIPTION
**Pull request by pine3ree**
Just a matter of taste: i think it looks uglier as a function static var. 
Also, in this way it's also available to all Message(s)

### CODE REVIEW

**Comment by akrabat** [comment]
Why does coverage go down?

**Comment by OptimusCrime** [comment]
Looks like an error in coveralls or something. These two files have identical coverage:
https://coveralls.io/builds/6341055/source?filename=Slim%2FDefaultServicesProvider.php
https://coveralls.io/builds/6390776/source?filename=Slim%2FDefaultServicesProvider.php

So does these:
https://coveralls.io/builds/6341055/source?filename=Slim%2FApp.php
https://coveralls.io/builds/6390776/source?filename=Slim%2FApp.php

The first of each is the current coverage in master (the last push) and the last is the coverage for this pull request.

**Comment by pine3ree** [comment]
@akrabat I was wondering the same thing :-)

**Comment by llvdl** [comment]
The lines of code with the `$valid` static variable that where in the function `withProtocolVersion` had code coverage. Those lines have been taken out and the total count of lines with code coverage has decreased because of this (static class variables don't count for code coverage).

**Pull request merged**
