### PR TITLE
Removes trailing slash from $_SERVER['DOCUMENT_ROOT'].

### LINKED ISSUE #653: Path parsing returns bad script name if Apache DocumentRoot includes trailing slash
`\Slim\Environment::__construct()` generates a bad `$env['SCRIPT_NAME']` if Apache `DocumentRoot` directive  includes a trailing slash.  Per the Apache [`DocumentRoot` documentation](http://httpd.apache.org/docs/2.2/mod/core.html#documentroot), the directive should not include a trailing slash.

### PR DESCRIPTION
**Pull request by jeremykendall**
Fixes #653.

### CODE REVIEW

**Comment by jeremykendall** [comment]
@petarov: I noticed [your comment](https://github.com/codeguy/Slim/commit/a35767746009ff818e6375b72f23a2cf7de5f1a4#commitcomment-4371264) on the `\Slim\Environment` HVVM commit.  Would you be willing to apply this fix to your local Slim install and see if it fixes your sandbox problem?  I'm interested to know if this PR fixes both my issue and yours.

**Comment by petarov** [comment]
@jeremykendall: I'll check it out asap  and I'll write back. thx!

**Comment by petarov** [comment]
I applied the #653 fix but sadly it did not solve my problem. I still get  `/sandbox/resource` instead of just `/resource`  in  `PATH_INFO` 

Like I wrote in the comment, I'm using an Apache Alias which points to a completely different server directory path than what comes in `DOCUMENT_ROOT`. I think the problem lays somewhere there but I've got little time to thoroughly trace it right now.

**Comment by jeremykendall** [comment]
@petarov I'm sorry to hear it didn't help, although it was kind of a shot in the dark.  If you're willing and able to share a small application that will recreate the issue, I'd be interested in looking at it.  Maybe we can put our heads together and get it sorted out.

**Comment by tuupola** [comment]
Just FYI. Slim routing is also broken when using [mod_vhost_alias](http://httpd.apache.org/docs/2.2/mod/mod_vhost_alias.html) I have a workaround for it but it breaks when upgrading from 2.3.1 to 2.3.3. Will do a proper bug report soon(ish).

**Comment by 4g0st1n0** [comment]
I have the same problem of @petarov. I'm using an Apache alias to point to a directory outside of virtual host document root.
After the upgrade from 2.3.1 t o 2.3.3 my routes does not works.
My alias is /backend/services. 
With request uri "/backend/services/search" before upgrade PATH_INFO = "/search", after upgrade PATH_INFO = "/backend/services/search"

**Comment by jeremykendall** [comment]
@4g0st1n0, @petarov, and @tuupola: Let's move the Apache alias discussion over to #655.  That's a separate issue than #653, which this PR fixes.

**Comment by codeguy** [comment]
Closing. This is fixed in the current release.

**Pull request closed without merging**
