### PR TITLE
Make PHP 5.5 the minimum supported version

### PR DESCRIPTION
**Pull request by akrabat**
Also update all other composer requirements to the "^" syntax.

### CODE REVIEW

**Comment by JoeBengalen** [comment]
Why drop php 5.4?

**Comment by akrabat** [comment]
Because of http://php.net/supported-versions.php - specifically: "Security Support Until": "14 Sep 2015"

**Comment by nhymxu** [comment]
I don't agree. Yes, php.net unsupport this, but many many server/ hosting provide continue using PHP 5.4 for a long time. 

I hate Laravel 5.1 because this require high PHP version than shared hosting support

**Comment by silentworks** [comment]
Why should we support an unsupported platform? If the PHP core team says they won't be supporting it after 14 Sep 2015, then why should anyone support it. 

The problem is not this change in the project nor is it Laravel 5.1, the problem is hosting companies being too lazy to make the switch.

**Comment by lalop** [comment]
I'm with @nhymxu on that, if the current code base work on php5.4 I don't see any good reason to define as uncompatible.
If in the next development php 5.4 appear to cause any issue so we can make this move at this moment.

**Comment by piotr-cz** [comment]
I'm for keeping min. requirement of php 5.4, at least until the codebase requires higher version.

As others pointed out, 5.4 is supported by the PHP core team till 14 Sep 2015, so ATM it is still actively supported and security support ends on 10 Jul 2016.

**Comment by silentworks** [comment]
Security support end 14 Sep 2015, not 10 Jul 2016.

**Comment by piotr-cz** [comment]
true

**Comment by codeguy** [comment]
We're 5.5+ from here on out.

**Comment by goldsky** [comment]
http://windows.php.net/

> PHP 5.4 series will be the last versions to support Windows XP and Windows 2003

Why we can't ignore Windows XP?
1. Most of big companies and industries (read: clients) don't have easy path to upgrade
2. Most of the users are still using IE8, especially in Asia (sucks but true)

So in our case, we, as developer, must try to set our system as low as the user/client can be, to experience their usage, even just to throw "Unsupported Browser" message.

If you drop the support <5.5 not because of its particular feature/function but rather its supporting reason, I'd like to ask you to consider it again.
Please.

**Comment by silentworks** [comment]
I think this thread has discussed this a lot already and many PHP projects are moving towards this direction also, we cant be kept at ransom by hosts, operating system or any of the likes. We are sticking with 5.5 and won't be changing this anytime soon. If you require support below 5.5, there is still Slim 2 available which is only taking security updates at the moment.

**Comment by piotr-cz** [comment]
It's still possible to install Slim3 on a local machine with PHP 5.5+ and deploy on server running PHP 5.4.

**Comment by tuupola** [comment]
Or you can just run composer with `--ignore-platform-reqs` switch.

**Comment by nandin-borjigin** [comment]
> It's still possible to install Slim3 on a local machine with PHP 5.5+ and deploy on server running PHP 5.4.
> It's incompatible now(Slim 3.4.2), it uses `::class` and it's a new feature in PHP 5.5

**Pull request merged**
