### PR TITLE
changed one line to match the rest of the docbloc's setup

### PR DESCRIPTION
**Pull request by johanneskonst**
just something i noticed looking throught the code. I hope i did this correctly

### CODE REVIEW

**Comment by johanneskonst** [comment]
@akrabat quick q: you merged #2070 but left this one open, does that mean that you don't accept pulls on 3.x branch, or are all changes done to 4.x with that milestone-3.7 being merged to 3.x when releasing 3.7?

Or better, if I want to contribute some more should I only concentrate my work on the 4.x branch and let you lot worry about what ends up where or do both 3.x and 4.x like I did this one?

Btw: i might have missed some docs on this (only read the CONTRIBUTING.md which was a bit puzzling) so apologies if this is already somewhere...

Thx!

**Comment by codeguy** [comment]
^ seconded. @akrabat We should update our contributing docs to clarify.

**Comment by akrabat** [comment]
Far more prosaically, I thought I was merging this one when I merged the other one!

**Comment by akrabat** [comment]
In general, I think we should continue to accept PRs for bug fixes and minor new features to 3.x for the time being at least.

**Pull request merged**
