### PR TITLE
Remove final from Container class

### PR DESCRIPTION
**Pull request by akrabat**

### CODE REVIEW

**Comment by geggleto** [comment]
YES PLZ! 1000x :+1:

**Comment by bradynpoulsen** [comment]
Is there a timeline for 3.1 to be released? It's kind of a bummer I can't test against `Slim\Container` until it is released

**Comment by mathmarques** [comment]
@bradynpoulsen You can test, just install the dev version like:

```
$ composer require slim/slim "3.x-dev"
```

**Comment by akrabat** [comment]
Currently planning for mid-next week.

**Pull request merged**
