### PR TITLE
optimized Slim_Route::matches

### PR DESCRIPTION
**Pull request by thomas-0816**
Patch for https://github.com/codeguy/Slim/issues/336

### CODE REVIEW

**Comment by codeguy** [comment]
This looks great. I'll pull this in this afternoon.

**Comment by codeguy** [comment]
The `Router::testRouterUrlFor` unit test fails. Can you refactor the `Router::urlFor` method to work with your new wildcard implementation?

**Comment by thomas-0816** [comment]
Looks like the new one is not yet in the repo, ... one moment ...

**Comment by codeguy** [comment]
That second commit only updates the unit test itself... does not touch the actual method. Did you rebase before committing?

**Comment by thomas-0816** [comment]
Sorry, I forgot to commit the Router.php, it should be available in https://github.com/codeguy/Slim/pull/357

**Comment by codeguy** [comment]
No worries. I figured you'd forgotten to commit something. Just pulled in the additional fix. Looks great! Appreciate your help.

**Pull request merged**
