### PR TITLE
Implemented late static binding

### PR DESCRIPTION
**Pull request by dannykopping**
Implemented late static binding on Slim class so that public/protected static functions can be overridden in deriving classes

### CODE REVIEW

**Comment by dannykopping** [comment]
Seems like the build is failing due to something else other than what I'm committing...
Maybe when I rebased I erroneously resolved a conflict?

**Comment by codeguy** [comment]
Did you rebase against the latest develop branch?

**Comment by dannykopping** [comment]
Yup

**Comment by codeguy** [comment]
Ok I'll merge locally and see what's up. Thanks!

**Pull request merged**
