### PR TITLE
* is missed

### PR DESCRIPTION
**Pull request by ares333**
I checked rfc3986

### CODE REVIEW

**Comment by vlakoff** [comment]
https://www.ietf.org/rfc/rfc3986.txt [Page 53]:

> The mark characters that are typically unsafe to decode,
> including the exclamation mark ("!"), asterisk ("*"), single-quote
> ("'"), and open and close parentheses ("(" and ")"), have been moved
> to the reserved set in order to clarify the distinction between
> reserved and unreserved and, hopefully, to answer the most common
> question of scheme designers.

**Comment by akrabat** [comment]
Why did you close?

**Comment by ares333** [comment]
I closed it because just one character was included in the patch and I didn't check the rfc very carefully.So I am not sure about it.😓

**Comment by vlakoff** [comment]
Note it's a negated character class. The characters it contains are *not* escaped.

Because the other characters – `!` `'` `(` `)` – from my quote above are also omitted, I guess the omission of `*` is on purpose.

**Comment by akrabat** [comment]
Thanks for noticing @ares333 & thanks @vlakoff for checking the regex. Seems that we're all good.

**Pull request closed without merging**
