### PR TITLE
Add (string) case in encodeSecureCookie call to hash_hmac

### PR DESCRIPTION
**Pull request by elgenie**
Per http://php.net/manual/en/function.hash-hmac.php, the second argument to hash_hmac is supposed to be a string. HHVM (http://www.hhvm.com) is more strict about checking the arguments.

(note: this functionality is no longer present on develop)

### CODE REVIEW

**Comment by elgenie** [comment]
This fixes SlimHttpUtilTest::testEncodeAndDecodeSecureCookie\* when run with HHVM.

**Comment by JoelMarcey** [comment]
Any update on if we can get this pull request merged? Thanks.

@cc ptarjan

**Comment by codeguy** [comment]
Will get it pulled into the forthcoming 2.4.1 release this weekend.

**Comment by codeguy** [comment]
Merged into release-2.4.1 branch.

**Comment by JoelMarcey** [comment]
@codeguy Thank you very much for this merge!

cc: ptarjan

**Pull request closed without merging**
