### PR TITLE
Changed the order of params and added in automatic naming #1052

### PR DESCRIPTION
**Pull request by silentworks**
Added in automatic route naming from #866 because it looks like its not optional to have a route without a name in FastRoute.

### CODE REVIEW

**Comment by akrabat** [comment]
Oh good. I have just come across this while looking at `devlop`.

I don't see that FastRoute cares about the name though, as the only thing that uses the name is Router::urlFor() as far as I can tell.

**Comment by silentworks** [comment]
@akrabat you are correct on this, I have now found the issue in the tests which led me to thinking this was necessary.

@codeguy it would seem that `$this->addRoute` method is looking for an string as the method and not an array, If I move this into a foreach loop it fixes the issues. I can see this only being necessary to do because we are still supporting the `$app->map` method. Let me know your thoughts.

**Comment by codeguy** [comment]
@silentworks Pull the latest commits. I asked Nikita to push out a new 0.4.0 FastRoute release that accepts an array of HTTP methods.

**Comment by silentworks** [comment]
@codeguy yes that worked.

**Pull request merged**
