### PR TITLE
Configuration

### PR DESCRIPTION
**Pull request by designermonkey**
Addresses request in #607 to supply nested array handling for configuration, accessible via a separated string key.

Removes older `config` method from `App` class instead of deprecates, as this will be applied in a major point version. (`3.0.0`)

### CODE REVIEW

**Comment by designermonkey** [comment]
I am in the process of learning how to use testing, so sorry for the lack of actual tests. I have tested this manually, and can't find any issues, but like most people, I am known to miss things.

**Comment by codeguy** [comment]
Thanks! Will have a look later this week.

**Comment by designermonkey** [comment]
Just realised that `$this->settings` inside the container should really be `$this->config`. I'll edit tonight.

**Comment by designermonkey** [comment]
Closed in favour of https://github.com/codeguy/Slim/pull/691 which is much simpler.

**Pull request closed without merging**
