### PR TITLE
Configuration

### PR DESCRIPTION
**Pull request by designermonkey**
First pass at Configuration handler.

Provides app configuration values stored as nested arrays, which can be accessed and stored using dot separated keys.

Works with already present `$app->config($name, $value);` method, but allows `ArrayAccess` to `$app->settings['dot.separated.key'];`

### CODE REVIEW

**Comment by designermonkey** [comment]
Balls. No unit test. Must sleep, will do it tomorrow.

**Comment by codeguy** [comment]
Cool. Get some unit tests added and make sure Travis CI is happy then I'll get this merged in.

**Comment by designermonkey** [comment]
I have begun work on a 'part 2' for this, to extend the functionality out to have a `ConfigurationHandler` loaded into the `Configuration` class.

This will allow scenarios like loading config values from a file for example.

This can be pulled in for now, as 'part 2' is built on top of this, and it will follow a very similar setup.

**Comment by designermonkey** [comment]
There's one test that fails: `testDerivedClassCanOverrideStaticFunction`, but I'm not sure if it's even needed anymore?

**Comment by codeguy** [comment]
Cool feel free to ignore and I'll have a look on my end.

**Pull request merged**
