### PR TITLE
Add a new PSR-17 factory to Psr17FactoryProvider

### PR DESCRIPTION
**Pull request by solventt**
There is curious performance benchmark of the PSR-7 and PSR-17 implementations (Guzzle, HttpSoft, Laminas, Nyholm, Slim) - https://github.com/devanych/psr-http-benchmark.

The fastest is HttpSoft, the slowest - Slim.

So I've added `HttpSoftPsr17Factory` to the Slim's factory set to give users the possibility to use the `HttpSoft` implementation of the PSR-7.

What was generally done:

**1\)** Adding `HttpSoftPsr17Factory::class` to the `$factories` property of the `Slim\Factory\Psr17\Psr17FactoryProvider` class

```php
protected static $factories = [
    SlimPsr17Factory::class,
    HttpSoftPsr17Factory::class,
    NyholmPsr17Factory::class,
    LaminasDiactorosPsr17Factory::class,
    GuzzlePsr17Factory::class,
];
```
I placed the class for the second position because it's the fastest implementation of the PSR-7 according to the benchmark. But the Slim's implementation remains in first place because I think it's normal to give priority to packages from the Slim's ecosystem.

**2\)** Adding the new `HttpSoftPsr17Factory` class to the Slim/Factory/Psr17 folder

**3\)** Adding the [httpsoft/http-message](https://github.com/httpsoft/http-message) and [httpsoft/http-server-request](https://github.com/httpsoft/http-server-request) packages to the `composer.json` file (--dev section)

**4\)** Adding `[HttpSoftPsr17Factory::class, HttpSoftServerRequest::class]` to the `provideImplementations()` method in the `ServerRequestCreatorFactoryTest` class

**5\)** Adding `[HttpSoftPsr17Factory::class, HttpSoftResponseFactory::class]` to the `provideImplementations()` method in the `AppFactoryTest` class

**6\)** Editing `README.md` (added a mention of the HttpSoft PSR-7 implementation along with other implementations)

### About tests

- There were: 420 tests, 779 assertions
- Became: 422 tests, 781 assertions

### CODE REVIEW

**Comment by l0gicgate** [comment]
This is a great contribution, I was not aware that our implementation was this slow. We should probably do some digging since the benchmarking code just seems to be instantiating the objects.

I also wasn't aware of the HttpSoft implementation!

We won't be able to merge this until we bump PHP lowest version support to 7.4 in about a month unfortunately

**Comment by l0gicgate** [comment]
We can deprecate PHP 7.3 as of Today @solventt if you would like to add that to this PR

**Comment by solventt** [comment]
@l0gicgate The conflict in composer.json has been resolved

**Review by l0gicgate — APPROVED** [review]
Thank you for this contribution @solventt

**Pull request merged**
