### PR TITLE
Don't send any content when it's a HEAD request.

### PR DESCRIPTION
**Pull request by solarissmoke**
Some servers (e.g., Apache) silently discard any content in response to a HEAD request, but others don't...

### CODE REVIEW

**Comment by codeguy** [comment]
Can you move your changes into the `\Slim\Http\Response::finalize` method?

**Comment by solarissmoke** [comment]
@codeguy I don't see how I can access the relevant properties of the `Request` (i.e., `isHead()`) from inside the `Response` class?

**Comment by codeguy** [comment]
Sorry. You're right. I was reading through this too fast. I'll get this pulled in today!

**Comment by codeguy** [comment]
Merged into release-2.3.3.

**Pull request closed without merging**
