### PR TITLE
batch config

### PR DESCRIPTION
**Pull request by elibyy**
added batch config option using php/ini/json/xml file

### CODE REVIEW

**Comment by silentworks** [comment]
This should not be in the core of Slim, you can already use third party libraries to do this as they all convert back to an PHP array in the end.

**Comment by elibyy** [comment]
yes but it's still make it much easier to load system configurations or make an installation config result file

**Comment by StJudeWasHere** [comment]
I'm with @silentworks too, I don't think this should go into Slim. I'd rather use a third party library when needed.

**Comment by prisis** [comment]
if you like you can you my config loader, https://github.com/n-brainwave/config. I will make some small changes today so it should work with slim

**Pull request closed without merging**
