### PR TITLE
Array access

### PR DESCRIPTION
**Pull request by StJudeWasHere**
This is an initial implementation for #398.

So far what it does is implement ArrayAccess in the Slim class and make the Request, Response, Environment and Router array accessible.

```
$app = new \Slim\Slim();
$app['response']['status'] = '500';
```

Maybe adding the Slim settings and the application middleware to the array access would be cool too, something like the Pimple's share method might be also useful.

I kind of like this DI container idea and I think it would allow Slim to evolve in a much more modular framework, what do you guys think?

### CODE REVIEW

**Comment by ziadoz** [comment]
Looks great.

Adding the Slim settings to the DI container would be really nice. Maybe then the `Slim::config()` method could be removed altogether?

It might also be worth implementing the `IteratorAggregate` interface as well, this way you could iteratate over the Slim object itself and access all the values in `$this->container`:

```
class Slim extends \ArrayAccess, \IteratorAggregate
{
    // ArrayAccess Methods...

    public function getIterator()
    {
        return new \ArrayIterator($this->container);
    }
}

$app = new Slim\Slim;
$app['foo'] = 'bar';

foreach ($di as $key => $value) {
    echo $key . ': ' . $value . "\n";
}

// foo: bar
```

I think the `share` and `protect` methods from Pimple would be a good addition too. The share method in particular would be really handy for storing something like a shared `PDO` object for an application.

**Comment by StJudeWasHere** [comment]
I added the settings and middleware to the ArrayAccess too. Some of the code in the Slim class could certainly be removed now.

**Comment by codeguy** [comment]
Thanks for your work on this. Let me play with it some this weekend and see what I think.

**Comment by ziadoz** [comment]
I think only the Slim object needs to be an array accessible DI container (like Pimple). Not so sure about settings or middleware.

**Comment by codeguy** [comment]
I agree only the Slim class should implement ArrayAccess and Pimple-like features. Applying to settings and middleware is just too much over-engineering. I don't think we need everything that Pimple provides, just basic parameter and object injection, and sharing/singletons.

**Comment by StJudeWasHere** [comment]
That was my feeling too, the last two commits would over-complicate the code. How would you go to make the settings and middleware accessible via ArrayAccess?

**Comment by StJudeWasHere** [comment]
I'm closing this one in favor of #433. It takes it from commit  7e5ed46 so ArrayAccess is only implemented in the Slim class.

**Pull request closed without merging**
