### PR TITLE
[4.x] Add method to customize the response factory class in the slim http psr17 factory

### PR DESCRIPTION
**Pull request by adriansuter**
This PR addresses #2712.

### CODE REVIEW

**Comment by adriansuter** [comment]
How would we be able to set a custom http decorator?

**Comment by l0gicgate** [comment]
You'd need to create your own `ResponseFactory` then use `AppFactory::setResponseFactory($yourCustomFactory)`

Then create your own `ServerRequestCreator` and do `ServerRequestCreatorFactory::setServerRequestCreator($yourCustomServerRequestCreator)`.

**Comment by adriansuter** [comment]
Wouldn't it be nice, that if you use one of the *built-in* PSR-7 implementations, then you just have to set the custom http decorator response factory to the slim http psr17 factory? Then Slim does automatically decorate as before.

**Comment by l0gicgate** [comment]
How many decorator libraries are there for PSR-7 decoration besides Slim-Http? I don't know of any.

**Comment by adriansuter** [comment]
Agree. So you think that this should not be an option? Either you use Slim-Http or you have to create your own response factory and server request creator.

**Comment by l0gicgate** [comment]
If we were to do it correctly, we'd need to create a decorator provider specifically for that purpose. Opening up the SlimHttp provider with that setter just seems like a hackish way to do it. So for now, unless users end up requesting that feature I don't think it's necessary.

**Pull request closed without merging**
