### PR TITLE
Fix Issue #1983: Throwable exception uncaught in Route.php

### PR DESCRIPTION
**Pull request by Starli0n**
Hi,

Could you please perform this pull request to fix the issue #1983.

Thanks

### CODE REVIEW

**Comment by dopesong** [comment]
Coverage decreased (-0.2%) to 97.003% - you should provide tests for this :)

**Comment by Starli0n** [comment]
@dopesong 

I added a test coverage for PHP7 only.

I do not know how to do better as far as `Throwable` appeared in PHP7.

**Comment by dopesong** [comment]
Check it here: https://github.com/slimphp/Slim/blob/3.x/tests/Handlers/PhpErrorTest.php#L88

**Comment by Starli0n** [comment]
As far as the coverage is performed in PHP5 and following the documentation http://php.net/manual/en/language.errors.php7.php#119652, the `catch (Throwable $t)` code is never reached in PHP5

``` php
try
{
   // Code that may throw an Exception or Error.
}
catch (Throwable $t)
{
   // Executed only in PHP 7, will not match in PHP 5
}
catch (Exception $e)
{
   // Executed only in PHP 5, will not be reached in PHP 7
}
```

Therefore I added `@codeCoverageIgnore` statement

**Comment by akrabat** [comment]
Thank you!

**Pull request closed without merging**
