### PR TITLE
Workaround for the failing unittests.

### PR DESCRIPTION
**Pull request by denshade**
Added an ob_get_clean in case of debugging. This fixes the annoying error of closed buffers mentioned in the unittests.
Extracted the rendering of Exceptions in a separate class. 
Also a few warnings were fixed.

### CODE REVIEW

**Comment by akrabat** [comment]
This is too big a change for Slim2. I'm also not seeing broken unit tests on 2.x.

**Comment by denshade** [comment]
This fixes https://github.com/slimphp/Slim/issues/1335. But ok.

**Comment by akrabat** [comment]
The main trouble is that you've done a fairly major refactor to fix this issue.

I was expecting to see a call `ob_get_clean()` just before https://github.com/slimphp/Slim/blob/2.x/Slim/Slim.php#L1375 or something similar.

**Comment by denshade** [comment]
I actually cleaned up a lot of warnings as well. Extracting PrettyExceptionRenderer was probably not necessary. Stuff like  
@var array Lookup hash of all route objects 
 => 
-     \* @var Route[]
  Allows for decent auto-completion in most IDEs and is nothing more than changing a docblock. So risk free. Also missing return statements are on my grumpy list. On the other side I understand 2.x is no longer in development. You can also just add the one line with ob_get_clean which will fix the issue.

**Pull request closed without merging**
