### PR TITLE
Add additional "reRun" method to Slim

### PR DESCRIPTION
**Pull request by ryan-mahoney**
No I haven't created any unit tests -- yet!

Just wanted to see if you could take a quick look at this change.  Essentially, this is to "reRun" Slim on a different HTTP method and URI so that you could call additional routes.  This code assumes that Slim has already been "run" and now it's being run again in the same request.

I had mentioned this a couple of months ago, the most common use case I can think of (mine) is when you want to call your own RESTful API from you own Slim based application... without creating a new and unnecessary HTTP request to your own server.  This has a lot of benefits.  The first, is speed, because some overhead is eliminated.  The second, is that exceptions from the reRuns will now bubble up.

### CODE REVIEW

**Comment by designermonkey** [comment]
I think Josh added a sub request method to Slim for the soon to be released version 3, let me have a look...

**Comment by designermonkey** [comment]
Aha!

here it is: https://github.com/codeguy/Slim/blob/develop/Slim/App.php#L1128 in the develop branch.

Is this the sort of thing you want? If so, then it's been tackled, if not, maybe we could work towards a common goal.

**Comment by codeguy** [comment]
Yep this is already available in the develop branch scheduled for the 3.0 release.

**Comment by ryan-mahoney** [comment]
LOL, I can believe I missed that!  Thanks

**Comment by ryan-mahoney** [comment]
So, I obtained the dev version.  Right off the bat, the code was generating a few errors.  Those errors could be fixed w/ two changes:

//parseHeaders expects Environment object
$headers->parseHeaders($environment);

//replace expects cookies to be and array, not an object
$cookies->replace((Array)$cookies);

At this point, I wasn't getting run-time errors, but it's returning an empty string for simple predefined routes.  I am using it with ReactPHP... so that could be a factor... will keep testing.

**Pull request closed without merging**
