### PR TITLE
Lazy-initialize class in \Slim\Route::setCallable()

### PR DESCRIPTION
**Pull request by mcuelenaere**
You don't want to construct all kinds of objects when setting up your routes, so don't initialize those objects until
the route is actually dispatched. Add some basic caching so multiple route dispatches don't result in multiple class
instantiations.

Note: I had to comment out RouteTest::testGetCallableAsClass(), as the callable is now a lambda function instead of an array. WDYT is the best way to solve this? (I think that the test was depending on an implementation detail and should just test whether the set callable is invoked when the route gets dispatched)

### CODE REVIEW

**Comment by anlutro** [comment]
Definitely this. I guess the "fix" for the broken test is to make `foo()` return something and do an `assertEquals` on `$route->dispatch()`.

**Comment by designermonkey** [comment]
I definitely like this. +1 from me.

**Comment by mcuelenaere** [comment]
@codeguy Any comments?

**Comment by poison** [comment]
I like this too! +1!

**Comment by haroldkyle** [comment]
This works much better, and helps the memory footprint a lot. +1

**Comment by scottux** [comment]
+1

**Comment by codeguy** [comment]
Scheduled for 2.4.3

**Comment by codeguy** [comment]
This is merged into the develop branch. Do you want to send a similar PR for the `release-2.4.3` branch?

**Comment by mcuelenaere** [comment]
Sure, see #779

**Pull request merged**
