### PR TITLE
Add Support for PATCH HTTP Verb

### PR DESCRIPTION
**Pull request by cwt137**
This patch provides explicit support for the PATCH HTTP Verb. I thought this would be nice since Backbone and other libraries support it.

### CODE REVIEW

**Comment by slowmove** [comment]
Really really want this to be implemented @codeguy :)

**Comment by spoonkojo** [comment]
I would also like to see PATCH included, thanks.

**Comment by bartlewis** [comment]
+1

**Comment by codeguy** [comment]
Sorry for the wait! Merged into the develop branch. Will become available in the next point release later this week.

**Comment by m-hume** [comment]
Glad to here its making its way through to release!

**Pull request merged**
