### PR TITLE
Matched routes should be saved so we can use getPattern() inside middleware hooks

### PR DESCRIPTION
**Pull request by vik-singh**
Save matched routes in dispatchRequest so you can use $router->getPattern() in various middleware

### CODE REVIEW

**Comment by silentworks** [comment]
@vik-singh can you update this so we can get it merged in please.

**Comment by codeguy** [comment]
@vik-singh Please rebase against latest develop branch changes. Let us know if you don't have time. I just want to make sure you have the opportunity to receive credit for the change.

**Comment by sarciszewski** [comment]
@vik-singh 

``` sh
git remote add upstream https://github.com/slimphp/Slim.git
# And then...
git fetch upstream develop
git checkout develop
git rebase upstream/develop
# Then, if there are no conflicts...
git push --force origin develop
```

**Comment by vik-singh** [comment]
Thanks Scott - will do it tonight

**Comment by vik-singh** [comment]
@codeguy @sarciszewski - it seems my changes are no longer applicable since we've changed to FastRoute - once this stabilizes I can test again with my app.  I am closing this pull request.

**Pull request closed without merging**
