### PR TITLE
#1669 added Routable::setPattern method

### PR DESCRIPTION
**Pull request by llvdl**
I don't know if this will work with caching as described in #1749

### CODE REVIEW

**Comment by akrabat** [comment]
what's the use-case for this?

**Comment by llvdl** [comment]
<s>If</s> I found the request at [issue 1669](https://github.com/slimphp/Slim/issues/1669). I'll leave it up to you to judge whether the use case is justified :)

**Comment by llvdl** [comment]
references #1669

**Comment by akrabat** [comment]
Thank you.

**Pull request merged**
