### PR TITLE
Match path items on whole words.

### PR DESCRIPTION
**Pull request by marionebl**
Hi there,

I recently ran into some issues with routing, where the callbacks for a route were executed that had a substring of the requested path in it.

An example:

``` php
$app->get("/me/", function() {
     echo("Nice to meet you.");
});

$app->get("/message/", function() {
     echo("No message for you this time.");
});
```

**GET /message/** would execute the callback for the "me" route in this scenario.

The proposed CR tries to fix this by checking if items in the route definition are candidates for matching on whole words and modifying the given parts of the matching regex.

Cheers,
marionebl

### CODE REVIEW

**Comment by designermonkey** [comment]
To me this boils down to specificity. As `me` is shorter than `message`, it should come after `message` in the list.

**Comment by marionebl** [comment]
@designermonkey 
Sorry, I am not sure what you want to say.

Do you want to say the mismatch is acceptable and should be handled by every single dev rearranging the route definitions?
Or do you think the problem should be handled by getting the `\Slim\Slim::Router::routes` array ordered by their string length?

**Comment by designermonkey** [comment]
> Do you want to say the mismatch is acceptable and should be handled by every single dev rearranging the route definitions?

When one defines routes that use regex patterns, specificity comes in to play. It does in every app I've used that has routes. Longer possible matches need to come before shorter ones. It's just the way it works.

I'm not saying your fix isn't valid, it surely is, to catch when it's not done right, but it's one of the things I learned, that's all.

**Comment by designermonkey** [comment]
Here's the first reference I could find as to what I meant.

http://laravel.io/topic/30/routes-first-in-first-out

**Comment by marionebl** [comment]
Ok, got it. Thank you for explaining!

**Comment by tuupola** [comment]
In Sinatra routes are matched in the order they are defined. The first route that matches the request will be executed. I find it confusing if execution order is defined by length of the route. Much less confusing to just set the order in source code.

**Comment by marionebl** [comment]
Had some thought on this and for me it is about wether the Slim::Slim::$request_method is to be thought of taking a regular expression as first parameter or a route string with placeholders matching the arguments in the given callback function. 

If it is the common view that the passed string should be seen as regex, I'll close this pull request. Implementing devs can solve this by passing `/^me$/`and `/^message$/` instead of `/me/`and `/message/`.

In this case the routing docs should get some hint about this, though.

**Comment by tuupola** [comment]
I expect **GET /me/** to match /me/ route and **GET /message/** to match /message/. Any other behavior is just plain wrong. I do not think passed string is a regex unless I specifically make it a regex. For for example:

```
$app->get("/^me*/", function() { ... }); /* Regex */
$app->get("/me/", function() { ... }); /* String */
```

**Comment by designermonkey** [comment]
What I mean when I talk about regex, is not whether you as a developer use a regex pattern when creating your route, it's how the router matches the string you've added, as it uses regex matching in it's processing of a route.

https://github.com/codeguy/Slim/blob/master/Slim/Route.php#L352

**Comment by marionebl** [comment]
BAD me did the first pull request without setting up the unit test env. 
The refactored version of this does the same concerning the the issue I want to solve. 
As a bonus it does not produce any new errors according to my local unit tests.

**Comment by codeguy** [comment]
@marionebl Can you move your regex changes into the `\Slim\Route::matchesCallback` method? I'd like to keep regex preparation isolated in that method. Thanks!

**Pull request closed without merging**
