### PR TITLE
Code and comment cleanup

### PR DESCRIPTION
**Pull request by JoeBengalen**
Some code and comment cleanups.

Changed the `Exception` to `InvalidArgumentException` in the `Route::setOutputBuffering()` method.

### CODE REVIEW

**Comment by JoeBengalen** [comment]
Should this exception also be more specific?
https://github.com/slimphp/Slim/blob/3.x/Slim/App.php#L82

**Comment by geggleto** [comment]
Ideally @JoeBengalen it should probably throw ... \ContainerInterfaceException

**Comment by geggleto** [comment]
Also if you would be so kind as to add a test case for that, as there currently is one to test for an exception should something bad be passed in for a container!

**Comment by JoeBengalen** [comment]
@geggleto You mean an implementation of this?
https://github.com/container-interop/container-interop/blob/master/src/Interop/Container/Exception/ContainerException.php

**Comment by geggleto** [comment]
Yes :) :+1:

**Comment by JoeBengalen** [comment]
Not sure if that would be right. Its not being thrown by the container, its an error from the application itself. It also requires slim to have its own implementation of the `ContainerException`.

I was more thinking of an `InvalidArgumentException`, as you should have passed an `array` or instance of `ContainerInterface`.

**Pull request merged**
