### PR TITLE
Don't rely on system setting for error_reporting level

### PR DESCRIPTION
**Pull request by ptarjan**
This test shouldn't fail if the system's php.ini setting differs on the error level (This was failing in HHVM's test environment)

### CODE REVIEW

**Comment by codeguy** [comment]
Is this issue limited to a particular unit test? And if so, should this solution be implemented in the Slim source code rather than in a unit test? I guess I'm just looking for more details about this issue.

**Comment by ptarjan** [comment]
This is a problem with Slim's unit test in `tests/Middleware/SessionCookieTest.php`, so indeed the fix should be in this repository. It is assuming that I haven't touched my error reporting level in my system's `php.ini` or else it fails.

I ran into this issue when testing slim on HHVM since we have different default error levels than PHP (we emit notices by default).

**Comment by codeguy** [comment]
Thanks for the clarification. Will get this pulled in soon.

**Comment by codeguy** [comment]
Merged into https://github.com/codeguy/Slim/commits/release-2.4.0

**Pull request closed without merging**
