### PR TITLE
Add throws ContainerException annotations

### PR DESCRIPTION
**Pull request by adriansuter**
The `\Psr\Container\ContainerInterface` may throw `\Interop\Container\Exception\ContainerException` exceptions. This PR annotates the methods in `\Slim\App` repspectively.

### CODE REVIEW

**Comment by adriansuter** [comment]
The PR #2668 did not add these annotations.

**Comment by l0gicgate** [comment]
it will never throw those exceptions. The method that throws those is `$container->get()` in the event that the requested offset isn’t present on the container. The thing is, all those offsets will always be present since we define them ourselves in the default service provider.

**Comment by adriansuter** [comment]
Well, that is true. Is it possible, that someone would unset those properties? Maybe by accident?

**Comment by l0gicgate** [comment]
It’s very unlikely that someone would go out of their way to unset those. We’re not going to annotate those exceptions.

**Comment by adriansuter** [comment]
What about a try catch inside the methods?

**Comment by l0gicgate** [comment]
Try/catch and then what? Throw again? It doesn’t make sense. It’s going to stay as is.

**Comment by adriansuter** [comment]
I'm fine with that. Sorry. I just thought to add a try/catch/ignore to make sure, no-one would issue that again. My IDE is actually warning me, because of non-annotated exceptions that could be possibly thrown. Never mind.

**Comment by l0gicgate** [comment]
The thing is if we annotate those exceptions then the end user will have to try/catch all those methods because their IDE is now going to complain. I’d rather us contain it at our level.

**Pull request closed without merging**
