### PR TITLE
Add text/plain to known content types

### PR DESCRIPTION
**Pull request by filips123**
Add `text/plain` to known content types in AbstractHandler.php.

### CODE REVIEW

**Comment by akrabat** [comment]
What is the use-case that this change is for?

**Comment by filips123** [comment]
It could be for some text based or CLI websites and applications.

**Comment by akrabat** [comment]
Do you have an actual app in production that needs this change? I'm struggling to imagine a text/plain website and haven't seen one in the wild.

**Comment by filips123** [comment]
No. This is just an idea, but it may be usable for someone.

**Comment by akrabat** [comment]
I think we'll wait for someone to have a production use-case for this one.

**Pull request closed without merging**
