### PR TITLE
[IN PROGRESS] Resolve middleware on demand

### PR DESCRIPTION
**Pull request by lalop**
Resolve middleware only if the route matches the requested path.

### CODE REVIEW

**Comment by codeguy** [comment]
@akrabat Did you want to make any further tweaks to this before merge?

**Comment by lalop** [comment]
I would like to push a second implementation before

**Comment by codeguy** [comment]
Sounds good. I'll wait until you are ready for merge.

**Comment by lalop** [comment]
here is a more generic solution https://github.com/slimphp/Slim/pull/1180

**Comment by akrabat** [comment]
I think we can close this in favour of #1180?

**Pull request closed without merging**
