### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Jud**
Changed Slim::request()->getHttpHeaders() to also pull in PHP_AUTH_\* headers for http basic username and password parsing.

### CODE REVIEW

**Comment by codeguy** [comment]
Hi Jud. Thanks for your code! I have a few more important issues to resolve first. Once those are smoothed over and pushed into `develop` and `master`, I'll be sure to pull this in.

**Comment by Jud** [comment]
Just trying to commit things I run into while using Slim, its a great framework.

**Comment by codeguy** [comment]
Absolutely! I really appreciate the help, and please continue doing so as you run into issues. There were two nasty bugs that were brought to my attention (one fixed, one outstanding). One those are both fixed, development will get back on schedule.

**Comment by codeguy** [comment]
Sorry for taking so long to pull this in. This is now available in the `develop` branch.

**Pull request merged**
