### PR TITLE
 I want to understand twice run slim application.

### PR DESCRIPTION
**Pull request by LeafChage**
I want to understand twice run slim application.

My application occurred error because of it.
I lost a day.

### CODE REVIEW

**Comment by l0gicgate** [comment]
Why are you calling the `App::run()` method twice?

There is no need to add this to the existing code base.

**Comment by LeafChage** [comment]
@l0gicgate 
It is my mistake.
But I was supposed to prevent, if it can not run twice.

**Comment by l0gicgate** [comment]
Okay, well it sounds like that's an issue on your end due to the logic that you're utilizing.

You can always extend the App class and overload the `App::run()` method to use your code or fork the repository and modify the code according to your use case.

I'm closing this PR.

**Comment by LeafChage** [comment]
Thanks

**Pull request closed without merging**
