### PR TITLE
File streaming

### PR DESCRIPTION
**Pull request by gmanricks**
# File Streaming

This PR adds two functions $app->sendProc() and $app->sendFile() as-well as a modified call loop which is backwards compatible.
### $app->sendProc($command, $contentType = "text-plain")

This function accepts a command and optionally a content type and will transfer the output to the client.
### $app->sendFile($file, $contentType = false)

This function accepts a URI either a local file or a remote URL, you can also specify a content type as the second parameter. If left blank the function will attempt to process and find an appropriate file type.

### CODE REVIEW

**Comment by codeguy** [comment]
Nice work!  Will get this into 2.4.

**Comment by codeguy** [comment]
What do you think about changing the method name `sendProc` to `sendProcess`... I'm less concerned about brevity and more about obviousness.

**Comment by gmanricks** [comment]
I renamed the function, also I forgot to mention I also added a function called setDownload([$filename]);

Which will set the header to force a download instead of the browser trying to open it. You can optionally pass in a filename to change the download's name to the specified string.

for example if you have a route for '/file'

and you run:

``` php
$app->setDownload();
```

it will force a download named 'file', whereas:

``` php
$app->setDownload("other.txt");
```

will download the contents of the route under the name 'other.txt'

**Comment by codeguy** [comment]
Haven't forgotten about this. This is next on my todo list. Hoping to get it pulled into the develop branch either tonight or tomorrow.

**Pull request merged**
