### PR TITLE
[develop] Fix PSR-2 coding style

### PR DESCRIPTION
**Pull request by zoontek**
I try to do a massive cleanup of the codebase.
Tell me what you think about it !

### CODE REVIEW

**Comment by JoeBengalen** [comment]
Note that the array short syntax requires PHP 5.4. Slim seems to also support version 5.3

**Comment by zoontek** [comment]
Slim 3 seems to need at least PHP 5.4, so I guess it's OK
https://github.com/slimphp/Slim/blob/develop/composer.json

**Comment by JoeBengalen** [comment]
Ah my mistake. I looked at the master requirements ;)

**Comment by codeguy** [comment]
I think this is all fine except for the EditorConfig thing. Can you remove that?

**Comment by zoontek** [comment]
No problem, not everyone use this indeed.

**Comment by prisis** [comment]
You can try to use https://github.com/FriendsOfPHP/PHP-CS-Fixer is much faster to get the right coding style :)

**Comment by zoontek** [comment]
Yep, it's already what I use, with the corrects fixers :)

**Comment by prisis** [comment]
Maybe you can create a ".php_cs" so all of us can use it, if @codeguy like the idea

**Comment by codeguy** [comment]
Just the formatting changes, please. I don't want anything in the repo that doesn't absolutely need to be there.

**Comment by zoontek** [comment]
I think it's all good. I don't see another optimisations.
Maybe PSR-4 autoloading, but in a different PR?

**Comment by JoeBengalen** [comment]
For psr-4 see #1075

**Comment by codeguy** [comment]
Crap. Can you rebase against the latest develop branch?

**Comment by zoontek** [comment]
No problem, It should be OK.

**Pull request merged**
